src/index.js
test/keyv.js

Ensuring we have a common default data structure for all stores will allow us to easily make changes in the future while keeping backwards compatibility.
For example, we can add an option to remove the timestamp wrapper if you're using Key as a persistent store. Without changing the option the default behaviour won't change, so existing users can upgrade without any code changes. New users can enable the option and benefit from reduced storage requirements.
Normalizing all timestamp data also allows us to very easily create migration tools to automatically migrate between stores.

Normalize data structure across stores

---

README.md

Resolves https://github.com/lukechilds/keyv/issues/31

Link to third-party storage adapters

---

README.md

Hello, I used this third party for creating a [self-hosted count service](https://github.com/Kikobeats/count) and it works like a charm, very happy with the result 🙂

Add goto-bus-stop/keyv-firestore third party adapter

---

src/index.js
test/keyv.js

Entries set with a TTL are not deleted, the `delete` call is made with a double prefix which does not delete the entry.
Corresponding issue: https://github.com/lukechilds/keyv/issues/108

Fix double prefix with TTL

---

src/index.js

I'm using this module (through npm.im/got) for a serverless function and I'm getting this warning:
```
3:31:45 PM: WARNING in ../node_modules/keyv/src/index.js 18:14-40
3:31:45 PM: Critical dependency: the request of a dependency is an expression
3:31:45 PM:  @ ../node_modules/cacheable-request/src/index.js
3:31:45 PM:  @ ../node_modules/got/dist/source/core/index.js
3:31:45 PM:  @ ../node_modules/got/dist/source/create.js
3:31:45 PM:  @ ../node_modules/got/dist/source/index.js
3:31:45 PM:  @ ./api.js
```
It's not technically a problem, but it is an annoyance and I'd love to avoid the warning.
This simply removes the dynamic require for static and lazy requires. Just a refactor. No functionality change here.

Remove dynamic require

---

README.md

I created a Keyv adapter for [Azure Table](https://docs.microsoft.com/en-us/azure/cosmos-db/table/table-support). I'm hoping to add it to the list of third-party storage adapters for visibility.
Thanks!

Added KeyV-AzureTable Adapter

---

packages/keyv/test/test.js
packages/sqlite/package.json
packages/sqlite/src/index.js

[node-sqlite3](https://github.com/mapbox/node-sqlite3) appears to be somewhat abandoned and has been racking up security vulnerabilities in its dependencies. This PR switches it to [better-sqlite3](https://github.com/JoshuaWise/better-sqlite3) which is more performant, supports more architectures, and is actively maintained.
This PR also switches to using [Bind Parameters](https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/api.md#binding-parameters) which resolves an issue I was experiencing when storing values that contain a single quote (`'`).
Note: I didn't really understand what was going on with the `TestAdapter`, so I just reverted [these changes](https://github.com/jaredwray/keyv/commit/ed094d0a0f7d492c5d0546dd5cd6cfe40f15708f#diff-a640cdc5ceede57b891b18b7ad8e7e0938980414 …

Convert sqlite3 to better-sqlite3

---

packages/keyv/src/index.js
packages/keyv/test/test.js

Because we don't know whether the `delete` would occur first or the next `set` operation. 
So just wait for the delete. Performance is not the point.

wait for the detele promise

---

README.md

The developer docs have not been updated to reflect that lerna was removed.

Remove references to lerna/bootstrap

---

packages/keyv/src/index.js

Hello,
I am new to Keyv and noticed that the rediss protocol is not supported.
I got an error when passing a rediss protocol URI.
```
> kv = new Keyv("rediss://example.com")
Uncaught:
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
at new NodeError (node:internal/errors:372:5)
at validateString (node:internal/validators:120:11)
at Module.require (node:internal/modules/cjs/loader:998:3)
at require (node:internal/modules/cjs/helpers:102:18)
at loadStore (/Users/airtoxin/repositories/app/node_modules/keyv/src/index.js:22:15)
at new Keyv (/Users/airtoxin/repositories/app/node_modules/keyv/src/index.js:50:22) {
code: 'ERR_INVALID_ARG_TYPE'
}
```
This PR improves this.
Of …

Add support for rediss protocol

---

packages/keyv/src/index.d.ts

Added `Promise`d return types for `serialize` and `deserialize`.

Added async deserialize/serialize function types

---

packages/keyv/src/index.d.ts

I'm a little unsure about the `StoredData` type I landed on, it's what I gathered based on the src here:
https://github.com/jaredwray/keyv/blob/main/packages/keyv/src/index.js#L155-L174
Also, `xo` is breaking my type:
I want:
`type StoredData<Value> = DeserializedData<Value> | string | null | undefined;`
...but it mistakenly replaces with:
`type StoredData<Value> = DeserializedData<Value> | string | undefined | undefined;`
Just a consideration: `prettier` tends to be the formatting standard in JS/TS and I've never seen an issue as glaring as ^ that while using it.

Add missing `getMany` optional method on Store interface

---

packages/keyv/src/index.d.ts

Revert "Add missing `getMany` optional method on Store interface"

---

packages/keyv/src/index.d.ts

Right now, calling `keyv.iterator()` from TypeScript code will result in a missing argument error:

Make iterator’s `namespace` parameter optional

---

packages/keyv/src/index.d.ts

Reinstates https://github.com/jaredwray/keyv/pull/362
The `undefined | undefined` type was happening via `xo`'s fix option due to a lint config which forbids the use of `null` (and converts to `undefined` (`@typescript-eslint/ban-types`). In hindsight, I'm not sure the `null` was correct there to begin with.

Reintroduce `getMany` optional method

---

packages/redis/README.md
packages/redis/src/index.js

fixed redis issue

---

packages/postgres/package.json

Maintenance update for Postgres
NA
NA
NO

postgres - upgrading ava to 4.3.1 and tsd to 0.22.0

---

packages/keyv/src/index.d.ts
packages/redis/package.json
packages/redis/src/index.d.ts
packages/redis/test/types.ts
tsconfig.json

Bug fix https://github.com/jaredwray/keyv/issues/404
https://github.com/jaredwray/keyv/issues/404
This may impact some typescript users 

Fix Keyv.Options type incorrectly defines store option type

---

README.md

updating readme with direct link to keyv package

updating readme with direct link to keyv package

---

packages/redis/src/index.js
packages/redis/test/test.js

fixed namespace clear issue

---

packages/compress-brotli/package.json
packages/compress-brotli/src/index.d.ts
packages/compress-brotli/src/index.js
packages/compress-gzip/src/index.d.ts
packages/compress-gzip/src/index.js
packages/keyv/src/index.d.ts

The goal with this is to update the main Keyv to handle compression in a more scalable manner and not do a ton of overwrites. 
- standardize the compression library with `compress(value, options)` and `decompress(value, options)`
- document a better structure for testing with the main Keyv library
- Remove anything unnecessary that was implemented
- Remove `compress` as it is no longer needed.

Compression Updates

---

docs/getting-started/index.md

Created a Getting Started Guide
for issue / feature #401

Getting Started Guide 🎉 

---

packages/redis/package.json

redis - removing @types/keyv as no longer needed

redis - removing @types/keyv as no longer needed

---

packages/website/site/docs/caching/caching.md
packages/website/site/docs/compression/compression.md
packages/website/site/docs/storage-adapters/storage-adapters.md
packages/website/site/docs/test-suite/index.md
packages/website/src/docs.ts

website - fixing docs page order

website - fixing docs page order

---

packages/memcache/README.md
packages/mysql/README.md
packages/offline/README.md

Issue #677

---

packages/postgres/src/index.d.ts
packages/postgres/src/index.js

Add Schema support for https://github.com/jaredwray/keyv/issues/667

✨: add schema support

---

packages/redis/src/index.js

When using `commandTimeout` on `ioredis` and if timeout is reached, this will throw an unhandled promise rejection. It is required to return the promise from that otherwise it's not possible to catch it.
> Edit:
We can listen to `process.on('unhandledrejection')` but this error happens for a `request` and we don't have the `response` object in that event handler.
Bug fix

Redis: Fix return on `set`

---

packages/test-suite/package.json

test-suite - upgrading sqlite3 to 5.1.6

test-suite - upgrading sqlite3 to 5.1.6

---

package.json

mono - updating c8 and @types/node to latest

mono - updating c8 and @types/node to latest

---

packages/etcd/src/index.ts

add type cast for an array element

---

packages/mysql/src/index.js

Exclude configuration options specific to keyv from the mysql2 connection options. This change fixes mysql2 invalid configuration warnings. MySQL2 will likely throw an error in future version. 
The change require neither additional tests nor documentation. The tests run with 100% code coverage.

Fix mysql2 invalid configuration (#788)

---

packages/mysql/src/pool.js

The original regular expression did not match URLs with special characters such as underscores and hyphens in the username, hostname, and path. This update modifies the regular expression pattern to include these characters, allowing for proper matching.
Regex pattern: /^(\w+):\/\/([\w_-]+)(?::(\w+))?@([\w.-]+)(?::(\d+))?\/(\w+)$/
Example URL: mysql://test_stg:test@test-stg-cluster.cluster-hqpowufs.ap-dqhowd-1.rds.amazonaws.com:3306/test_beta
Please review and consider merging this update. Thank you!

Update regular expression to support special characters in URL

---

packages/mysql/src/pool.js
packages/mysql/test/test.js

parsing connection string with special characters

parsing connection string with special characters

---

packages/redis/src/index.ts

Unfortunately, if the redis database has many entries, the current approach using recursion can run into a maximum call stack size exceeded exception.

fix: maximum call stack size exceeded

---

packages/redis/src/index.ts

Revert breaking change in Redis constructor

---

packages/redis/README.md
packages/redis/package.json
packages/redis/src/index.ts
packages/redis/src/types.ts
packages/redis/test/test.ts

add useRedisSets option  

---

packages/keyv/src/index.d.ts

One overload with `options?: { raw?: false }` and one with `options: { raw: true }` allows being specific about the return type for each.
So, the behavior is unchanged but it becomes easier for external libraries to write an interface with a correct *partial* implementation.
My use-case: I'm working on a library that expects a keyv-like object passed in. The user is allowed to pass in a different implementation, as long as the basic `get`, `set` and `delete` exist. But they don't need to provide an implementation for the `{ raw: true }` variant. So, I'm trying to write an interface that corresponds to that, which `new Keyv<string>(...)` conforms to. This is hard/impossible to do without some `as any` hacks right now, but the change in this commit makes it possible.
I tried this by …

Replace `get<Raw>(...)` with an overload

---

packages/redis/src/index.ts
packages/redis/test/test.ts

Fixing issue #902. 
https://github.com/jaredwray/keyv/issues/902

redis - fixing bug with ioredis and useRedisSets

---

packages/redis/src/index.ts

When using Redis and `useRedisSets=true`, it's possible to end up with a mismatch between the keys listed in the namespace set and the actual key/values in Redis.
**Quick Review of Current Functionality**
- The `set` op takes place in two steps, the key/value is set and then the key is added to the namespace set. 
- The `delete` op takes place in two steps, the key/value is deleted and then the key is removed from the namespace set.
- The `clear` op takes place in two steps, the keys are retrieved from the namespace set and then they are deleted (including the namespace set itself).
Problems can arise when steps become intermixed and state changes take place in between steps 1 of 2 of certain ops.
**Example Problem 1 - key/value in Redis but key not listed in namespace set (actual …

Fix: Redis race conditions with .set, .delete. and .clear when useRedisSets=true

---

packages/redis/test/test.ts

redis - adding in testing on delete when not using redis sets

redis - adding in testing on delete when not using redis sets

---

packages/redis/src/index.ts

In @keyv/redis, modified the delete() and clear() functions to use UNLINK instead of DEL to improve performance.
DEL is blocking and can take longer the larger the key size, whereas UNLINK is non-blocking and perform the operation in O(1) for each key removed regardless of its size.
**What kind of change does this PR introduce?** feature

feat: [GH-910] Switch to use Redis UNLINK instead of DEL

---

packages/mysql/src/index.ts

mysql - moving to using query instead of execute
This is based on the following issue: https://github.com/jaredwray/keyv/issues/170 
@banianxd and @Jeffthedevlol FYI. - One thing that would be great is if we could validate with a unit test that this fixes the issue.

mysql - moving to using query instead of execute

---

packages/redis/src/index.ts
packages/redis/test/test.ts

This PR fixes a bug in `@keyv/redis`where if `useRedisSets` is false and clear is called when no keys exist an error is thrown.
- The error thrown was
```txt
ReplyError {
command: {
args: [],
name: 'unlink',
},
message: 'ERR wrong number of arguments for \'unlink\' command',
}
```
- I added tests for `useRedisSets` true/false so this should not regress in the future for either case.

fix(redis): do not error calling clear with empty keys and `useRedisSets` false

---

packages/keyv/src/index.ts
packages/keyv/src/stats-manager.ts
packages/keyv/test/stats-manager.test.ts
packages/keyv/test/test.ts

adding in stats to keyv

---

packages/tiered/package.json

tiered - upgrading eslint to 9.1.1

tiered - upgrading eslint to 9.1.1

---

package.json
packages/compress-brotli/package.json
packages/compress-brotli/src/index.ts
packages/compress-brotli/src/types.ts
packages/compress-brotli/test/test.ts
packages/compress-brotli/test/types.ts
packages/compress-gzip/src/index.ts
packages/keyv/README.md
packages/keyv/package.json
packages/keyv/src/index.ts
packages/keyv/test/test.ts
packages/memcache/package.json
packages/memcache/src/index.ts
packages/serialize/README.md
packages/serialize/package.json
packages/serialize/src/index.ts
packages/serialize/test/test.ts
packages/serialize/tsconfig.dist.json
packages/serialize/tsconfig.json
packages/test-suite/package.json

closes #1029
Removes the deprecated `json-buffer`. The new package `@keyv/serialize` is now independent and can be refactored later easily to improve the default serialization functionality.

feat: remove deprecated json-buffer dependency

---

.github/workflows/tests.yaml
docker-compose-arm64.yaml
docker-compose.yaml
packages/memcache/package.json

memcache - upgrading typescript to 5.4.5

memcache - upgrading typescript to 5.4.5

---

package.json
packages/postgres/package.json
packages/postgres/src/index.ts

mono - upgrading vitest to 1.6.0

mono - upgrading vitest to 1.6.0

---

packages/mongo/src/index.ts
packages/mongo/src/types.ts
packages/mongo/test/test.ts

Fix.  The Mongodb adapter failed to shutdown gracefully leaving the nodejs process in a hung state (open sockets).  The disconnect method was implement to allow the client api to call it in a "finally" clause or dispose method.

#1084 Implement disconnect for mongodb adapter to support a graceful shutdown.

---

packages/compress-gzip/src/index.ts
packages/keyv/src/index.ts
packages/keyv/test/test.ts

Add validation method for storage adapters

---

packages/compress-brotli/src/index.ts
packages/compress-brotli/src/types.ts
packages/compress-brotli/test/test.ts
packages/compress-gzip/src/index.ts
packages/compress-gzip/test/test.ts

#1117
compress-gzip - fix: set any value before getting value

compress-gzip - fix: set any value before getting value

---

packages/keyv/src/index.ts
packages/keyv/test/keyv-hooks.test.ts

I was using the package and noticed that preDelete is not called, and postDelete doesn't return the keys that where deleted.
I just added proper calling of the hooks

fix: preDelete hook not called when a single key is deleted

---

packages/redis/package.json

redis - moving keyv to be star as a dependency

redis - moving keyv to be star as a dependency

---

packages/keyv/README.md
packages/keyv/src/index.ts
packages/keyv/test/test.ts

keyv - adding in store property

Keyv - adding in store property

---

packages/keyv/README.md

keyv - removing awesome module content as it is in getting started guide

keyv - removing awesome module content as it is in getting started guide

---

packages/website/site/docs/caching/caching-javascript.md

website - updating caching documentation to use Cacheable with Keyv

website - updating caching documentation to use Cacheable with Keyv

---

packages/etcd/package.json
packages/etcd/src/index.ts
packages/etcd/test/test.ts
packages/keyv/src/index.ts

close #1227 
To make the test pass, I modified the package.json of the etcd package so that keyv points to the package in the workspace.

feat: adding in etcd as iterable

---

packages/redis/README.md
packages/redis/src/index.ts
packages/redis/test/cluster.ts
packages/redis/test/test.ts

**What kind of change does this PR introduce?**
This PR is a follow-up on issue #1222 which I reported earlier. It adds an option to the adapter's API called `noNamespacesAffectsAll` and if is set to `true` and `namespace` is undefined:
- `clear` method will use `FLUSHDB` command
- `iterator` method will return all keys regardless of having a namespace prefix
The behavior of these methods will remain the same in cluster mode.
This option has a default value of `false` for backward compatibility so this PR does not introduce a breaching change.

feat: add noNamespaceAffectsAll option

---

packages/keyv/src/index.ts
packages/keyv/test/test.ts

ref: https://github.com/jaredwray/keyv/issues/1244

fix: handle errors in store.set method and return result status

---

packages/redis/README.md
packages/redis/package.json
packages/redis/src/index.ts
packages/redis/test/cluster.ts
packages/redis/test/test.ts

**What kind of change does this PR introduce?**
This PR introduces these non-braking features and improvements:
- `iterator` method works on clusters
- `clear` method works on clusters
- `setMany` method uses `MGET` operation instead of transactions which improves its performance

redis: clear and iterator methods support Clusters

---

packages/postgres/README.md
packages/postgres/src/index.ts
packages/postgres/src/types.ts
packages/postgres/test/test.ts

feat: ability to use unlogged table on Postgres

---

packages/serialize/src/index.ts
packages/serialize/test/test.ts

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...
fixes #1303

Bugfix: use Object.prototype for correct usage of hasOwnProperty

---

packages/keyv/src/index.ts
packages/keyv/test/keyv-test.test.ts

feat: adding in deleteMany and getMany

feat: adding in deleteMany and getMany

---

packages/keyv/README.md
packages/keyv/src/index.ts
packages/keyv/test/keyv-hooks.test.ts

keyv - fix: making PRE_SET work correctly on set function
#1359

keyv - fix: making PRE_SET work correctly on set function

---

packages/compress-brotli/package.json

compress-brotli - fix: moving Keyv to a peer dependency

compress-brotli - fix: moving Keyv to a peer dependency

---

packages/keyv/README.md
packages/sqlite/package.json
packages/sqlite/test/iterator.test.ts
packages/sqlite/vitest.config.ts

sqlite - chore: testing iterator with useKeyPrefix and documentation
#1431

sqlite - chore: testing iterator with useKeyPrefix and documentation
