- README.md
- src/index.js
- test/keyv.js
> Allow specifying custom `serialize` and `deserialize` functions

- README.md
Add the DynamoDB storage adapter into the third party adapters section
> docs(readme): add a reference to keyv-dynamodb

- README.md
https://github.com/lukechilds/keyv/pull/43#issuecomment-471081525
> API documentation: clarification that the Map-like instance methods return a promise

- packages/postgres/package.json
- packages/postgres/src/index.js
> Revert "removed from postgres package"

- packages/mysql/src/index.js
> replace with mysql pool

- packages/mongo/package.json
- packages/mongo/src/index.js
- packages/mongo/test/test.js
> initial implementation

- packages/keyv/src/index.js
- packages/test-suite/src/values.js
> fixed bigint and symbol

- packages/keyv/src/index.js
- packages/keyv/test/test.js
- packages/sqlite/src/index.js
- packages/sqlite/test/test.js
- packages/test-suite/src/index.js
- packages/test-suite/src/iterator.js
- packages/test-suite/test/unit.js
> Expose Iterables

- packages/keyv/src/index.js
- packages/mysql/src/index.js
- packages/mysql/src/pool.js
- packages/mysql/test/test.js
> iterables for mysql

- packages/keyv/src/index.js
- packages/postgres/src/index.js
- packages/postgres/src/pool.js
- packages/postgres/test/test.js
> implement iterables for postgres

- packages/keyv/src/index.js
- packages/mongo/src/index.js
- packages/mongo/test/test.js
> implement iterables for mongo

- packages/keyv/src/index.js
- packages/mongo/src/index.js
- packages/redis/src/index.js
- packages/redis/test/test.js
> implement iterables for redis

- packages/etcd/package.json
- packages/keyv/package.json
- packages/memcache/package.json
- packages/memcache/test/test.js
- packages/mongo/package.json
- packages/mysql/package.json
- packages/postgres/package.json
- packages/redis/package.json
- packages/sqlite/package.json
- packages/test-suite/package.json
- packages/test-suite/src/official.js
> upgrade ava

- packages/keyv/package.json
- packages/keyv/src/index.js
- packages/keyv/test/test.js
> support compress

- packages/keyv/test/test.js
> added test for lines

- packages/keyv/src/index.d.ts
~~This covers my use-cases and most (all?) of those enumerated in the `README.md`, but doesn't necessarily cover everything the constructor actually may handle (e.g. compression options).~~
This copies over types from [https://github.com/DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/keyv/index.d.ts)
Closes #271
> Add valid constructor calls and arguments to types

- .github/workflows/tests.yaml
- packages/keyv/src/index.js
- packages/offline/README.md
- packages/offline/package.json
- packages/offline/src/index.d.ts
- packages/offline/src/index.js
- packages/offline/test/test.js
- packages/offline/tsconfig.json
- packages/redis/test/test.js
> initial commit for supporting offline

- packages/keyv/src/index.d.ts
- packages/keyv/src/index.js
- packages/keyv/test/test.js
> covered all lines

- packages/redis/src/index.d.ts
> fixed type issue in redis

- packages/memcache/src/index.js
- packages/memcache/test/test.js
> fixed memchache uncovered lines

- README.md
Add document for "iterator" usage
> doc: add iterator usage document

- packages/etcd/src/index.js
- packages/etcd/test/test.js
- packages/memcache/package.json
- packages/mongo/test/test.js
- packages/mysql/src/index.js
- packages/mysql/test/test.js
- packages/offline/src/index.js
- packages/postgres/src/index.js
- packages/postgres/test/test.js
- packages/redis/src/index.js
- packages/test-suite/src/api.js
- packages/test-suite/src/iterator.js
- packages/test-suite/src/values.js
- packages/test-suite/test/unit.js
> covered lines in test

- packages/sqlite/package.json
> added pify as dependency

- packages/keyv/src/index.d.ts
Please see [issue 326](https://github.com/jaredwray/keyv/issues/326)
> Remove parameter initializer from type declarations

- packages/tiered/src/index.js
Currently this set promise is left dangling. I think its better to wait for it.
> Wait for set promise in tiered

- packages/tiered/README.md
> added readme

- packages/keyv/src/index.js
> fix memory leak

- README.md
- packages/keyv/README.md
- packages/memcache/README.md
- packages/memcache/package.json
> keyv memcache update 337

- README.md
- SECURITY.md
This PR updates the README.md root file in the GitHub repository to discuss how to use this repo. It also updates the SECURITY.md to reflect the security policy.
> Documentation: How to use our Mono Repo #324

- packages/redis/src/index.js
Removing console.log messages on the redis package
it currently outputs log messages for debugging
no log message output for debugging in production
No
> redis - removing console.log messages from previous bug fix

- packages/sqlite/package.json
> sqlite - upgrading sqlite3 to 5.0.9

- packages/sqlite/package.json
> sqlite - upgrading ava to 4.3.1

- packages/mysql/package.json
> mysql - upgrading ava to 4.3.1 and tsd to 0.22.0

- packages/etcd/package.json
> etcd - upgrading tsd, typescript, and ava to latest

- packages/tiered/package.json
> tiered - upgrading tsd to 0.22.0 and ava to 4.3.1

- packages/memcache/package.json
> memcache - upgrade ava to 4.3.1

- packages/redis/package.json
redis - upgrading ioredis to 5.2.2
> redis - upgrading ioredis to 5.2.2

- packages/redis/package.json
redis - upgrading ava to 4.3.1
> redis - upgrading ava to 4.3.1

- packages/offline/package.json
offline - upgrading ava to 4.3.1
> offline - upgrading ava to 4.3.1

- packages/keyv/package.json
> keyv - upgrading ava to 4.3.1

- packages/keyv/package.json
keyv - upgrading eslint to 8.22.0
> keyv - upgrading eslint to 8.22.0

- packages/keyv/package.json
> keyv - upgrading xo to 0.51.0

- packages/sqlite/package.json
sqlite - upgrading sqlite3 to 5.0.11
> sqlite - upgrading sqlite3 to 5.0.11

- packages/memcache/test/test.js
- packages/sqlite/package.json
sqlite - upgrading xo to 0.51.0
> sqlite - upgrading xo to 0.51.0

- packages/etcd/package.json
- packages/memcache/package.json
- packages/memcache/test/test.js
> etcd - upgrading xo to 0.51.0

- packages/etcd/package.json
etcd - removing webpack as no longer needed
> etcd - removing webpack as no longer needed

- .github/workflows/tests.yaml
- packages/etcd/README.md
- packages/etcd/package.json
- packages/etcd/src/index.js
etcd - upgrading cockatiel to 3.0.0 with exponential backoff on retry
Updating the policy to do exponential backoff instead of constant retry.
> etcd - upgrading cockatiel to 3.0.0 with exponential backoff on retry

- packages/keyv/package.json
keyv - moving to minimal node engine support of 14
> keyv - moving to minimal node engine support of 14

- packages/etcd/package.json
etcd - adding webpack because of dependency tree
> etcd - adding webpack because of dependency tree

- packages/compress-brotli/README.md
adding in readme for @keyv/compress-brotli
> adding in readme for @keyv/compress-brotli

- packages/compress-brotli/package.json
- packages/memcache/package.json
- packages/mongo/package.json
- packages/mysql/package.json
- packages/offline/package.json
- packages/redis/package.json
- packages/sqlite/package.json
- packages/test-suite/package.json
- packages/tiered/package.json
moving to serialize the test suites
> moving to serialize the test suites

- packages/tiered/README.md
updating tiered readme to have correct urls
> updating tiered readme to have correct urls

- packages/compress-gzip/README.md
compress-gzip - adding in readme
> compress-gzip - adding in readme

- packages/compress-gzip/README.md
- packages/keyv/README.md
Readme updates to support compression packages
> Readme updates to support compression packages

- packages/memcache/package.json
memcache - upgrading ava to 4.3.3
> memcache - upgrading ava to 4.3.3

- packages/memcache/package.json
memcache - upgrading typescript to 4.8.2
> memcache - upgrading typescript to 4.8.2

- packages/redis/package.json
redis - upgrading ioredis to 5.2.3
> redis - upgrading ioredis to 5.2.3

- packages/redis/package.json
redis - upgrading ava to 4.3.3
> redis - upgrading ava to 4.3.3

- packages/test-suite/package.json
test-suite - upgrading bignumber.js to 9.1.0
> test-suite - upgrading bignumber.js to 9.1.0

- packages/test-suite/package.json
test-suite - upgrading ava to 4.3.3
> test-suite - upgrading ava to 4.3.3

- packages/offline/package.json
offline - upgrading ava to 4.3.3
> offline - upgrading ava to 4.3.3

- packages/offline/package.json
offline - upgrading tsd, typescript, and ts-node to latest
> offline - upgrading tsd, typescript, and ts-node to latest

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
updating contributing documentation and templates
> updating contributing documentation and templates

- packages/sqlite/package.json
sqlite - upgrading sqlite3 to 5.1.1
> sqlite - upgrading sqlite3 to 5.1.1

- packages/sqlite/package.json
sqlite - upgrading ava to 4.3.3
> sqlite - upgrading ava to 4.3.3

- packages/sqlite/package.json
- packages/sqlite/src/index.d.ts
sqlite - upgrading xo to 0.52.3 includes index.d.ts type changes
> sqlite - upgrading xo to 0.52.3 includes index.d.ts type changes

- packages/postgres/package.json
postgres - upgrading ava to 4.3.3
> postgres - upgrading ava to 4.3.3

- packages/postgres/package.json
postgres - upgrading pg to 8.8.0
> postgres - upgrading pg to 8.8.0

- packages/mysql/package.json
mysql - upgrading ava to 4.3.3
> mysql - upgrading ava to 4.3.3

- packages/mysql/package.json
mysql - upgrading typescript to 4.8.3 and tsd to 0.24.1
> mysql - upgrading typescript to 4.8.3 and tsd to 0.24.1

- packages/etcd/package.json
> etcd - upgrading ava to 4.3.3

- packages/etcd/package.json
- packages/etcd/src/index.d.ts
etcd - upgrading xo to 0.52.3 and index.d.ts with types
> etcd - upgrading xo to 0.52.3 and index.d.ts with types

- packages/etcd/package.json
etcd - removing pify as no longer needed
> etcd - removing pify as no longer needed

- packages/tiered/package.json
tiered - upgrading ava to 4.3.3
> tiered - upgrading ava to 4.3.3

- packages/keyv/package.json
> keyv - upgrading ava to 4.3.3

- packages/compress-brotli/package.json
- packages/compress-brotli/src/index.d.ts
- packages/compress-brotli/src/index.js
- packages/compress-gzip/src/index.d.ts
- packages/compress-gzip/src/index.js
- packages/keyv/src/index.d.ts
> Revert "Compression Updates"

- packages/keyv/package.json
keyv - upgrading eslint to 8.24.0
> keyv - upgrading eslint to 8.24.0

- packages/keyv/package.json
> keyv - upgrading xo to 0.52.3

- packages/memcache/package.json
memcache - upgrading typescript to 4.8.4
> memcache - upgrading typescript to 4.8.4

- packages/sqlite/package.json
sqlite - upgrading sqlite3 to 5.1.2
> sqlite - upgrading sqlite3 to 5.1.2

- packages/sqlite/package.json
sqlite - upgrading typescript to 4.8.4
> sqlite - upgrading typescript to 4.8.4

- packages/sqlite/package.json
sqlite - upgrading xo to 0.52.4
> sqlite - upgrading xo to 0.52.4

- packages/mysql/package.json
mysql - upgrading xo to latest
> mysql - upgrading xo to latest

- packages/etcd/package.json
> xo - upgrading xo to 0.52.4

- packages/etcd/src/index.d.ts
- packages/memcache/src/index.d.ts
- packages/mongo/src/index.d.ts
- packages/mysql/src/index.d.ts
- packages/offline/src/index.d.ts
- packages/postgres/src/index.d.ts
- packages/redis/src/index.d.ts
- packages/sqlite/src/index.d.ts
- packages/tiered/src/index.d.ts
> added fix for value

- packages/compress-brotli/src/index.d.ts
- packages/compress-brotli/test/test.js
- packages/compress-gzip/package.json
- packages/compress-gzip/src/index.d.ts
- packages/compress-gzip/test/test.js
- packages/test-suite/src/compression.js
> fixed ts issue

- docs/caching/caching-javascript.md
- docs/caching/caching-node.md
- docs/getting-started/index.md
> Created How to Implement Caching in Javascript Page

- packages/keyv/package.json
> keyv - upgrading ava to 5.0.1

- packages/keyv/package.json
keyv - upgrading eslint to 8.26.0
> keyv - upgrading eslint to 8.26.0

- packages/keyv/package.json
> keyv - upgrading xo to 0.52.4

- packages/memcache/package.json
memcache - upgrading ava to 5.0.1
> memcache - upgrading ava to 5.0.1

- packages/redis/package.json
redis - upgrading ava to 5.0.1
> redis - upgrading ava to 5.0.1

- packages/redis/package.json
redis - upgrading xo to 0.52.4
> redis - upgrading xo to 0.52.4

- packages/redis/package.json
redis - upgrading ioredis to 5.2.4
> redis - upgrading ioredis to 5.2.4

- packages/test-suite/package.json
test-suite - upgrading ava to 5.0.1
> test-suite - upgrading ava to 5.0.1

- packages/offline/package.json
offline - upgrading ava to 5.0.1
> offline - upgrading ava to 5.0.1

- packages/offline/package.json
offline - upgrading xo to 0.52.4
> offline - upgrading xo to 0.52.4

- packages/compress-brotli/package.json
compress-brotli - upgrading ava to 5.0.1
> compress-brotli - upgrading ava to 5.0.1

- packages/compress-brotli/package.json
compress-brotli - upgrading xo to 0.52.4
> compress-brotli - upgrading xo to 0.52.4

- packages/compress-gzip/package.json
compress-gzip - upgrading ava to 5.0.1
> compress-gzip - upgrading ava to 5.0.1

- packages/keyv/src/index.d.ts
> Fix CompressionAdapter interface definition

- packages/redis/src/index.d.ts
> redis issue 558 disconnect definition fix

- packages/keyv/src/index.js
- packages/keyv/test/test.js
> fixed issue 559

- packages/sqlite/package.json
sqlite - upgrading xo to 0.53.1
> sqlite - upgrading xo to 0.53.1

- packages/sqlite/package.json
sqlite - upgrading typescript to 4.9.3
> sqlite - upgrading typescript to 4.9.3

- packages/sqlite/package.json
sqlite - upgrading ava to 5.1.0
> sqlite - upgrading ava to 5.1.0

- packages/postgres/package.json
postgres - upgrading ava to 5.1.0
> postgres - upgrading ava to 5.1.0

- packages/mysql/package.json
mysql - upgrading typescript to 4.9.3
> mysql - upgrading typescript to 4.9.3

- packages/mysql/package.json
mysql - upgrading ava to 5.1.0
> mysql - upgrading ava to 5.1.0

- packages/etcd/package.json
> etcd - upgrading ava to 5.1.0

- packages/etcd/package.json
- packages/memcache/package.json
> etcd - upgrading xo to 0.53.1

- package.json
mono - upgrading @types/node to 18.11.9
> mono - upgrading @types/node to 18.11.9

- packages/tiered/package.json
tiered - upgrading ava to 5.1.0
> tiered - upgrading ava to 5.1.0

- .github/workflows/tests.yaml
- package.json
- packages/compress-brotli/package.json
- packages/compress-gzip/package.json
- packages/etcd/package.json
- packages/keyv/package.json
- packages/memcache/package.json
- packages/mongo/package.json
- packages/mysql/package.json
- packages/offline/package.json
- packages/postgres/package.json
- packages/redis/package.json
- packages/sqlite/package.json
- packages/sqlite/test/test.js
- packages/test-suite/package.json
- packages/tiered/package.json
migrating to c8 for code coverage reporting
> migrating to c8 for code coverage reporting

- docs/caching/amazon-documentdb-storage-adapter.md
Added guide to creating a keyv instance using a DocumentDB storage adapter
> amazon documentdb storage adapter guide

- package.json
mono - upgrading @types/node to 18.11.10
> mono - upgrading @types/node to 18.11.10

- packages/keyv/package.json
> keyv - upgrading xo to 0.53.1

- packages/keyv/package.json
keyv - upgrading typescript to 4.9.3
> keyv - upgrading typescript to 4.9.3

- packages/memcache/package.json
memcache - upgrading typescript to 4.9.3
> memcache - upgrading typescript to 4.9.3

- packages/keyv/package.json
keyv - upgrading tsd to 0.25.0
> keyv - upgrading tsd to 0.25.0

- packages/keyv/package.json
keyv - upgrading eslint to 8.29.0
> keyv - upgrading eslint to 8.29.0

- packages/keyv/package.json
> keyv - upgrading ava to 5.1.0

- packages/memcache/package.json
memcache - upgrading ava to 5.1.0
> memcache - upgrading ava to 5.1.0

- packages/redis/package.json
- packages/redis/src/index.d.ts
redis - upgrading typescript to 4.9.3
> redis - upgrading typescript to 4.9.3

- packages/redis/package.json
redis - upgrading ava to 5.1.0
> redis - upgrading ava to 5.1.0

- packages/test-suite/package.json
test-suite - upgrading ava to 5.1.0
> test-suite - upgrading ava to 5.1.0

- packages/offline/package.json
offline - upgrading ava to 5.1.0
> offline - upgrading ava to 5.1.0

- packages/offline/package.json
- packages/offline/src/index.d.ts
- packages/offline/src/index.js
offline - upgrading xo to 0.53.1
> offline - upgrading xo to 0.53.1

- packages/compress-brotli/package.json
- packages/compress-brotli/test/test.js
compres-brotli - upgrading xo to 0.53.1
> compres-brotli - upgrading xo to 0.53.1

- packages/compress-brotli/package.json
compress-brotli - upgrading ava to 5.1.0
> compress-brotli - upgrading ava to 5.1.0

- packages/compress-gzip/package.json
compress-gzip - upgrading xo to 0.53.1
> compress-gzip - upgrading xo to 0.53.1

- packages/compress-gzip/package.json
compress-gzip - upgrading ava to 5.1.0
> compress-gzip - upgrading ava to 5.1.0

- packages/compress-gzip/package.json
compress-gzip - upgrading pako to 2.1.0
> compress-gzip - upgrading pako to 2.1.0

- README.md
Adding package https://github.com/TimMikeladze/keyv-arango to the "Third-party Storage Adapters" to list in the README.
> Added `keyv-arango` to  3rd party storage adapters

- packages/keyv/README.md
adding in arango storage adapter reference
> adding in arango storage adapter reference

- packages/sqlite/package.json
sqlite - upgrading sqlite3 to 5.1.4
> sqlite - upgrading sqlite3 to 5.1.4

- packages/keyv/package.json
keyv - upgrading typescript to 4.9.4
> keyv - upgrading typescript to 4.9.4

- packages/keyv/package.json
keyv - upgrading eslint to 8.31.0
> keyv - upgrading eslint to 8.31.0

- packages/memcache/package.json
memcache - upgrading typescript to 4.9.4
> memcache - upgrading typescript to 4.9.4

- packages/redis/package.json
redis - upgrading typescript to 4.9.4
> redis - upgrading typescript to 4.9.4

- packages/test-suite/package.json
test-suite - upgrading bignumber.js to 9.1.1
> test-suite - upgrading bignumber.js to 9.1.1

- packages/offline/package.json
offline - upgrading typescript to 4.9.4
> offline - upgrading typescript to 4.9.4

- packages/compress-gzip/package.json
compress-gzip - upgrading typescript to 4.9.4
> compress-gzip - upgrading typescript to 4.9.4

- .github/workflows/tests.yaml
updating the github actions to latest v3
> updating the github actions to latest v3

- packages/compress-brotli/package.json
compress-brotoli - adding in c8 for unit testing
> compress-brotoli - adding in c8 for unit testing

- packages/compress-brotli/package.json
compress-brotli - upgrading typescript to 4.9.4
> compress-brotli - upgrading typescript to 4.9.4

- packages/compress-gzip/package.json
compress-gzip - cleaning up dev dependencies
> compress-gzip - cleaning up dev dependencies

- packages/sqlite/package.json
sqlite - upgrading ava to 5.1.1
> sqlite - upgrading ava to 5.1.1

- packages/postgres/package.json
postgres - upgrading ava to 5.1.1
> Postgres   upgrading ava to 5.1.1

- packages/mysql/package.json
> mysql - uprading ava to 5.1.1

- packages/mysql/src/index.js
mysql - removing options that are invalid
> mysql - removing options that are invalid

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.0.1
> mysql - upgrading mysql2 to 3.0.1

- packages/etcd/package.json
> Etcd   upgrading ava to 5.1.1

- packages/tiered/package.json
tiered - upgrading ava to 5.1.1
> tiered - upgrading ava to 5.1.1

- packages/memcache/package.json
memcache - upgrading typescript to 4.9.5
> memcache - upgrading typescript to 4.9.5

- packages/offline/package.json
offline - upgrading ava to 5.1.1
> offline - upgrading ava to 5.1.1

- packages/offline/package.json
offline - upgrading typescript to 4.9.5
> offline - upgrading typescript to 4.9.5

- packages/compress-gzip/package.json
compress-gzip - upgrading ava to 5.1.1
> compress-gzip - upgrading ava to 5.1.1

- packages/compress-gzip/package.json
compress-gzip - upgrading typescript and eslint to latest
> compress-gzip - upgrading typescript and eslint to latest

- packages/compress-brotli/package.json
compress-brotli - upgrading ava to 5.1.1
> compress-brotli - upgrading ava to 5.1.1

- packages/compress-brotli/package.json
compres-brotli - upgrading typescript to 4.9.5
> compres-brotli - upgrading typescript to 4.9.5

- packages/redis/package.json
redis - upgrading ava to 5.1.1
> redis - upgrading ava to 5.1.1

- packages/redis/package.json
redis - upgrading typescript to 4.9.5
> redis - upgrading typescript to 4.9.5

- packages/redis/package.json
redis - upgrading ioredis to 5.3.0
> redis - upgrading ioredis to 5.3.0

- packages/keyv/package.json
> keyv - upgrading ava to 5.1.1

- packages/keyv/package.json
keyv - upgrading eslint and typescript to latest
> keyv - upgrading eslint and typescript to latest

- .gitignore
- packages/website/site/docs/storage-adapters/storage-adapters.md
- packages/website/src/docs.ts
website - adding in storage adapters fix
> website - adding in storage adapters fix

- .github/workflows/deploy-website.yml
- packages/website/src/docs.ts
Website - fixing build with path issues
> Website - fixing build with path issues

- packages/sqlite/package.json
- packages/sqlite/src/index.d.ts
> removing better-sqlite3 library and types

- packages/compress-brotli/src/index.js
- packages/compress-brotli/test/test.js
> add deserialize validation to avoid empty values

- .github/workflows/deploy-website.yml
website - fixing the deployment on pull request
> website - fixing the deployment on pull request

- packages/sqlite/package.json
- packages/website/package.json
sqlite - upgrading typescript to 4.9.5
> sqlite - upgrading typescript to 4.9.5

- packages/sqlite/package.json
sqlite - upgrading c8 and ava to latest
> sqlite - upgrading c8 and ava to latest

- packages/postgres/package.json
postgres - upgrading typescript, ava, and c8 to latest
> postgres - upgrading typescript, ava, and c8 to latest

- packages/postgres/package.json
postgres - upgrading pg to 8.9.0
> postgres - upgrading pg to 8.9.0

- packages/mysql/package.json
mysql - upgrading typescript, ava, and c8 to latest
> mysql - upgrading typescript, ava, and c8 to latest

- packages/mysql/package.json
mysql - upgradin mysql2 to 3.1.2
> mysql - upgradin mysql2 to 3.1.2

- packages/etcd/package.json
etcd - upgrading typescript, ava, anc c8 to latest
> etcd - upgrading typescript, ava, anc c8 to latest

- packages/tiered/package.json
tiered - upgrading typescript, ava, and c8 to latest
> tiered - upgrading typescript, ava, and c8 to latest

- packages/test-suite/package.json
test-suite - updating publish to only need the dist folder
> test-suite - updating publish to only need the dist folder

- packages/memcache/package.json
memcache - upgrading ava to 5.2.0
> memcache - upgrading ava to 5.2.0

- packages/redis/package.json
redis - upgrading c8 to 7.13.0
> redis - upgrading c8 to 7.13.0

- packages/redis/package.json
redis - upgrading ava to 5.2.0
> redis - upgrading ava to 5.2.0

- packages/redis/package.json
redis - upgrading ioredis to 5.3.1
> redis - upgrading ioredis to 5.3.1

- packages/test-suite/package.json
test-suite - upgrading ava to 5.2.0
> test-suite - upgrading ava to 5.2.0

- packages/test-suite/package.json
test-suite - upgrading c8 to 7.13.0
> test-suite - upgrading c8 to 7.13.0

- packages/offline/package.json
offline - upgrading ava to 5.2.0
> offline - upgrading ava to 5.2.0

- packages/offline/package.json
offline - upgrading c8 to 7.13.0
> offline - upgrading c8 to 7.13.0

- packages/compress-brotli/package.json
compress-brotli - upgrading ava to 5.2.0
> compress-brotli - upgrading ava to 5.2.0

- packages/compress-gzip/package.json
compress-gzip - upgrading eslint to 5.54.0
> compress-gzip - upgrading eslint to 5.54.0

- packages/compress-gzip/package.json
compress-gzip - upgrading c8 to 7.13.0
> compress-gzip - upgrading c8 to 7.13.0

- packages/compress-gzip/package.json
compress-gzip - upgrading ava to 5.2.0
> compress-gzip - upgrading ava to 5.2.0

- packages/keyv/test/test.js
keyv - adding in test with non const ttl
> keyv - adding in test with non const ttl

- packages/keyv/test/test.js
- packages/redis/package.json
- packages/redis/test/test.js
redis - adding in ttl with non const test
> redis - adding in ttl with non const test

- packages/postgres/src/index.js
> add schema in get method

- packages/postgres/README.md
- packages/postgres/src/index.d.ts
- packages/postgres/src/index.js
- packages/postgres/test/test.js
Postgres - adding in schema support
> Postgres - adding in schema support

- packages/postgres/test/test-ssl.js
- packages/postgres/test/test.js
postgres - cleaning up testing uri
> postgres - cleaning up testing uri

- packages/sqlite/package.json
sqlite - upgrading sqlite3 to 5.1.6
> sqlite - upgrading sqlite3 to 5.1.6

- packages/postgres/package.json
postgres - upgrading pg to 8.10.0
> postgres - upgrading pg to 8.10.0

- packages/mysql/package.json
- packages/postgres/test/test.js
mysql - upgrading mysql2 to 3.2.0
> mysql - upgrading mysql2 to 3.2.0

- packages/etcd/package.json
etcd - upgrading cockatiel to 3.1.1
> etcd - upgrading cockatiel to 3.1.1

- packages/website/package.json
website - upgrading docula and fs-extra to latest
> website - upgrading docula and fs-extra to latest

- packages/website/site/_includes/doc.njk
- packages/website/site/_includes/shared/head.njk
- packages/website/site/index.njk
- packages/website/site/versions.njk
> add custom head title tag

- packages/memcache/package.json
memcache - upgrading typescript to 5.0.3
> memcache - upgrading typescript to 5.0.3

- packages/memcache/package.json
memcache - upgrading memjs to 1.3.1
> memcache - upgrading memjs to 1.3.1

- packages/redis/package.json
redis - upgrading typescript to 5.0.3
> redis - upgrading typescript to 5.0.3

- packages/test-suite/package.json
test-suite - upgrading typescript and @ava/typescript to latest
> test-suite - upgrading typescript and @ava/typescript to latest

- packages/compress-gzip/package.json
compress-gzip - upgrading typescript and related modules to latest
> compress-gzip - upgrading typescript and related modules to latest

- packages/compress-brotli/package.json
compress-brotli - upgrading typescript and webpack to latest
> compress-brotli - upgrading typescript and webpack to latest

- packages/keyv/package.json
keyv - upgrading typescript to 5.0.3
> keyv - upgrading typescript to 5.0.3

- packages/keyv/package.json
keyv - upgrading eslint to 8.37.0
> keyv - upgrading eslint to 8.37.0

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.2.1
> mysql - upgrading mysql2 to 3.2.1

- packages/etcd/package.json
- packages/etcd/src/index.ts
- packages/memcache/package.json
- packages/test-suite/package.json
- packages/test-suite/src/api.ts
- packages/test-suite/src/compression.ts
- packages/test-suite/src/index.ts
- packages/test-suite/src/iterator.ts
- packages/test-suite/src/values.ts
> etcd - upgrading xo to 0.54.1

- packages/tiered/package.json
tiered - upgrading xo and eslint to latest
> tiered - upgrading xo and eslint to latest

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.2.3
> mysql - upgrading mysql2 to 3.2.3

- packages/mysql/src/pool.js
mysql - moving to correct pool configuration object
> mysql - moving to correct pool configuration object

- packages/memcache/package.json
memcache - removing @types/keyv
> memcache - removing @types/keyv

- docs/caching/caching-nestjs.md
docs - adding in how to for caching with nest.js
> docs - adding in how to for caching with nest.js

- packages/memcache/package.json
memcache - upgrading typescript to 5.0.4
> memcache - upgrading typescript to 5.0.4

- packages/redis/package.json
redis - upgrading typescript to 5.0.4
> redis - upgrading typescript to 5.0.4

- packages/redis/package.json
redis - upgrading ioredis to 5.3.2
> redis - upgrading ioredis to 5.3.2

- packages/test-suite/package.json
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)test-suite - upgrading typescript to 5.0.4
> test-suite - upgrading typescript to 5.0.4

- packages/offline/package.json
offline - upgrading typescript to 5.0.4
> offline - upgrading typescript to 5.0.4

- packages/compress-brotli/package.json
compress-brotli - upgrading typescript to 5.0.4
> compress-brotli - upgrading typescript to 5.0.4

- packages/compress-gzip/package.json
compress-gzip - upgrading eslint to 8.40.0
> compress-gzip - upgrading eslint to 8.40.0

- packages/compress-gzip/package.json
compress-gzip - upgrading typescript to 5.0.4
> compress-gzip - upgrading typescript to 5.0.4

- packages/mongo/src/index.ts
mongo - removing the filename for an index
> mongo - removing the filename for an index

- packages/postgres/package.json
postgres - upgrading pg to 8.11.0
> postgres - upgrading pg to 8.11.0

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.3.1
> mysql - upgrading mysql2 to 3.3.1

- package.json
mono - upgrading webpack to 5.83.1
> mono - upgrading webpack to 5.83.1

- package.json
mono - upgrading typescript and @types/node to latest
> mono - upgrading typescript and @types/node to latest

- packages/mysql/src/pool.js
- packages/mysql/test/test.js
mysql - fixing url parsing of mysql (#808 issue)
> mysql - fixing url parsing of mysql (#808 issue)

- packages/website/site/_includes/assets/css/styles/index.css
- packages/website/site/_includes/doc.njk
- packages/website/site/_includes/shared/head.njk
- packages/website/site/_includes/shared/homeHeader.njk
- packages/website/site/index.njk
website - updating with fork me on github ribbon
> website - updating with fork me on github ribbon

- packages/keyv/package.json
keyv - upgrading eslint to 8.42.0
> keyv - upgrading eslint to 8.42.0

- packages/memcache/package.json
memcache - upgrading typescript to 5.1.3
> memcache - upgrading typescript to 5.1.3

- packages/redis/package.json
redis - upgrading delay to 6.0.0
> redis - upgrading delay to 6.0.0

- packages/compress-gzip/package.json
compress-gzip - upgrading eslint modules to latest
> compress-gzip - upgrading eslint modules to latest

- packages/compress-brotli/package.json
compress-brotli - upgrading c8 and webpack to latest
> compress-brotli - upgrading c8 and webpack to latest

- .github/workflows/tests.yaml
> nodejs version 20 support

- packages/mysql/src/index.ts
> (mysql) use async/await instead promises on connection

- package.json
mono - upgrading webpack to 5.87.0
> mono - upgrading webpack to 5.87.0

- package.json
mono - upgrading typescript to 5.1.3
> mono - upgrading typescript to 5.1.3

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.3.5
> mysql - upgrading mysql2 to 3.3.5

- packages/etcd/package.json
etcd - upgrading typescript to 5.1.3
> etcd - upgrading typescript to 5.1.3

- packages/etcd/package.json
> etcd - upgrading c8 to 8.0.0

- packages/etcd/package.json
> etcd - upgrading ava to 5.3.1

- packages/tiered/package.json
- packages/tiered/test/test.ts
tiered - removed delay module as no longer needed
> tiered - removed delay module as no longer needed

- packages/tiered/package.json
tiered - upgrading ava and c8 to latest
> tiered - upgrading ava and c8 to latest

- packages/etcd/src/index.ts
- packages/etcd/src/types.ts
- packages/etcd/test/test.ts
> add iterator on etcd adapter

- packages/memcache/package.json
memcache - upgrading typescript to 5.1.6
> memcache - upgrading typescript to 5.1.6

- packages/redis/package.json
- packages/test-suite/package.json
- packages/test-suite/src/helper.ts
- packages/test-suite/src/index.ts
- packages/test-suite/src/iterator.ts
- packages/tiered/test/test.ts
test-suite - replacind delay module with helper for all packages
> test-suite - replacind delay module with helper for all packages

- packages/compress-gzip/package.json
compress-gzip - upgrading eslint and @ava/typescript to latest
> compress-gzip - upgrading eslint and @ava/typescript to latest

- packages/compress-brotli/package.json
compress-brotli - upgrading c8 to 8.0.0
> compress-brotli - upgrading c8 to 8.0.0

- packages/compress-brotli/package.json
compress-brotli - upgrading webpack to 5.88.1
> compress-brotli - upgrading webpack to 5.88.1

- README.md
> Added `keyv-momento` to 3rd party storage adapters

- packages/keyv/README.md
- packages/website/site/docs/index.md
@eaddingtonwhite - just fyi that I am adding this to a couple other readme locations so it is more visible. Thanks!
> adding keyv-momento to other md files

- packages/website/site/_includes/shared/homeData.njk
Latest's Releases > Latest Releases
Just noticed this on https://keyv.org.
> Fix typo in homeData.njk

- packages/compress-brotli/package.json
compress-brotli - removing xo duplication
> compress-brotli - removing xo duplication

- packages/postgres/package.json
- packages/website/src/docs.ts
postgres - upgrading pg to 8.11.1
> postgres - upgrading pg to 8.11.1

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.5.1
> mysql - upgrading mysql2 to 3.5.1

- packages/etcd/package.json
> etcd - upgrading xo to 0.55.0

- packages/etcd/package.json
etcd - typescript upgraded to 5.1.6
> etcd - typescript upgraded to 5.1.6

- packages/tiered/package.json
tiered - upgrading xo to 0.55.0
> tiered - upgrading xo to 0.55.0

- packages/tiered/package.json
tiered - upgrading eslint to 8.45.0
> tiered - upgrading eslint to 8.45.0

- package.json
- packages/keyv/package.json
- packages/memcache/package.json
- packages/mongo/package.json
- packages/mysql/package.json
- packages/offline/package.json
- packages/postgres/package.json
- packages/redis/package.json
- packages/sqlite/package.json
mono - updating xo, typescript, @types/node, and webpack to latest
> mono - updating xo, typescript, @types/node, and webpack to latest

- packages/etcd/package.json
- packages/etcd/src/index.ts
- packages/redis/src/types.ts
- packages/test-suite/src/values.ts
fixing eslint issues with types on modules etcd, redis, and test-suite
> fixing eslint issues with types on modules etcd, redis, and test-suite

- packages/redis/package.json
redis - upgrading timekeeper to 2.3.1
> redis - upgrading timekeeper to 2.3.1

- packages/test-suite/package.json
test-suite - upgrading timekeeper to 2.3.1
> test-suite - upgrading timekeeper to 2.3.1

- packages/compress-brotli/package.json
compress-brotli - upgrading c8 to 8.0.1
> compress-brotli - upgrading c8 to 8.0.1

- packages/compress-brotli/package.json
compres-brotli - upgrading webpack to 5.88.2
> compres-brotli - upgrading webpack to 5.88.2

- packages/compress-brotli/package.json
compress-brotli - upgrading compress-brotli to 1.3.9
> compress-brotli - upgrading compress-brotli to 1.3.9

- packages/compress-gzip/package.json
compress-gzip - upgrading eslint to 8.46.0
> compress-gzip - upgrading eslint to 8.46.0

- packages/keyv/package.json
keyv - upgrading eslint to 8.46.0
> keyv - upgrading eslint to 8.46.0

- packages/keyv/package.json
keyv - upgrading timekeeper to 2.3.1
> keyv - upgrading timekeeper to 2.3.1

- packages/postgres/package.json
postgres - upgrading pg to 8.11.3
> postgres - upgrading pg to 8.11.3

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.6.0
> mysql - upgrading mysql2 to 3.6.0

- packages/etcd/package.json
> etcd - upgrading xo to 0.56.0

- packages/etcd/package.json
etcd - upgrading c8 and webpack to latest
> etcd - upgrading c8 and webpack to latest

- packages/etcd/package.json
etcd - upgrading etcd3 to 1.1.2
> etcd - upgrading etcd3 to 1.1.2

- packages/tiered/package.json
tiered - upgrading c8, eslint, and xo to latest
> tiered - upgrading c8, eslint, and xo to latest

- package.json
mono - upgrading xo, c8, and webpack to latest
> mono - upgrading xo, c8, and webpack to latest

- packages/memcache/package.json
memcache - upgrading typescript to 5.2.2
> memcache - upgrading typescript to 5.2.2

- packages/redis/package.json
redis - upgrading tsd to 0.29.0
> redis - upgrading tsd to 0.29.0

- packages/test-suite/package.json
test-suite - upgrading bignumber.js to 9.1.2
> test-suite - upgrading bignumber.js to 9.1.2

- packages/offline/package.json
offline - upgrading tsd to 0.29.0
> offline - upgrading tsd to 0.29.0

- packages/compress-gzip/package.json
compress-gzip - upgrading eslint to 8.48.0
> compress-gzip - upgrading eslint to 8.48.0

- packages/compress-brotli/package.json
compress-brotli - upgrading tsd to 0.29.0
> compress-brotli - upgrading tsd to 0.29.0

- packages/sqlite/package.json
sqlite - upgrading @keyv/test-suite to latest
> sqlite - upgrading @keyv/test-suite to latest

- packages/sqlite/package.json
- packages/sqlite/src/index.ts
sqlite - replaced pify with util.promisify
> sqlite - replaced pify with util.promisify

- packages/postgres/package.json
postgres - upgrading tsd to 0.29.0
> postgres - upgrading tsd to 0.29.0

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.6.1
> mysql - upgrading mysql2 to 3.6.1

- packages/tiered/package.json
tiered - upgrading eslint to 8.49.0
> tiered - upgrading eslint to 8.49.0

- packages/memcache/package.json
memcache - upgrading @types/memjs to 1.3.1
> memcache - upgrading @types/memjs to 1.3.1

- packages/test-suite/package.json
test-suite - upgrading @types/json-bigint to 1.0.2
> test-suite - upgrading @types/json-bigint to 1.0.2

- packages/compress-brotli/package.json
compress-brotli - upgrading compress-brotli to 1.3.11
> compress-brotli - upgrading compress-brotli to 1.3.11

- packages/compress-gzip/package.json
compress-gzip - upgrading @types/pako to 2.0.1
> compress-gzip - upgrading @types/pako to 2.0.1

- packages/compress-gzip/package.json
compress-gzip - upgrading eslint to 8.51.0
> compress-gzip - upgrading eslint to 8.51.0

- packages/keyv/package.json
keyv - upgrading eslint to 8.51.0
> keyv - upgrading eslint to 8.51.0

- packages/keyv/package.json
keyv - upgrading tsd to 0.29.0
> keyv - upgrading tsd to 0.29.0

- README.md
- docker-compose-arm64.yaml
- package.json
adding in arm64 support for docker compose
> adding in arm64 support for docker compose

- packages/memcache/package.json
memcache v4 - upgrading @types/memjs to 1.3.2
> memcache v4 - upgrading @types/memjs to 1.3.2

- packages/compress-gzip/package.json
compress-gzip v4 - upgrading pako types and eslint to latest
> compress-gzip v4 - upgrading pako types and eslint to latest

- packages/compress-brotli/package.json
compress-brotli v4 - upgrading webpack to 5.89.0
> compress-brotli v4 - upgrading webpack to 5.89.0

- packages/compress-brotli/package.json
compress-brotli v4 - upgrading brotli to 1.3.12
> compress-brotli v4 - upgrading brotli to 1.3.12

- package.json
mono repo v5 - upgrading @types/node and webpack to latest
> mono repo v5 - upgrading @types/node and webpack to latest

- packages/memcache/package.json
memcache v5 - upgrading @types/memjs to 1.3.3
> memcache v5 - upgrading @types/memjs to 1.3.3

- docker-compose-arm64.yaml
- package.json
adding in amd64 support on test:services:start
> adding in amd64 support on test:services:start

- packages/compress-brotli/package.json
compress-brotli - upgrading webpack to 5.89.0
> compress-brotli - upgrading webpack to 5.89.0

- packages/compress-brotli/package.json
compress-brotli - upgrading brotli to 1.3.12
> compress-brotli - upgrading brotli to 1.3.12

- packages/postgres/package.json
sqlite - upgrading @types/pg to 8.10.9
> sqlite - upgrading @types/pg to 8.10.9

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.6.3
> mysql - upgrading mysql2 to 3.6.3

- packages/tiered/package.json
tiered - upgrading eslint to 8.54.0
> tiered - upgrading eslint to 8.54.0

- package.json
mono - upgrading @types/node to 20.9.2
> mono - upgrading @types/node to 20.9.2

- packages/keyv/test/keyv-hooks.test.ts
keyv - updating hooks test descriptions
> keyv - updating hooks test descriptions

- packages/compress-gzip/package.json
compress-gzip - upgrading eslint to 8.55.0
> compress-gzip - upgrading eslint to 8.55.0

- packages/memcache/package.json
memcache - upgrading typescript and types to latest
> memcache - upgrading typescript and types to latest

- packages/test-suite/package.json
test-suite - upgrading sqlite3 to 5.1.7
> test-suite - upgrading sqlite3 to 5.1.7

- packages/test-suite/package.json
test-suite - upgrading types for json to latest
> test-suite - upgrading types for json to latest

- packages/offline/package.json
offline - upgrading tsd and ts-node to latest
> offline - upgrading tsd and ts-node to latest

- packages/compress-gzip/package.json
compress-gzip - upgrading eslint to 8.56.0
> compress-gzip - upgrading eslint to 8.56.0

- packages/compress-gzip/package.json
compress-gzip - upgrading tsd and types to latest
> compress-gzip - upgrading tsd and types to latest

- packages/compress-brotli/package.json
compress-brotli - upgrading tsd and c8 to latest
> compress-brotli - upgrading tsd and c8 to latest

- packages/keyv/package.json
keyv - upgrading eslint to 8.56.0
> keyv - upgrading eslint to 8.56.0

- packages/test-suite/package.json
test-suite - removing sqlite3 as no longer needed
> test-suite - removing sqlite3 as no longer needed

- packages/redis/src/index.ts
- packages/redis/test/test.ts
https://github.com/jaredwray/keyv/pull/964
https://github.com/jaredwray/keyv/pull/964
> redis - fixing error again on calling clear with empty keys

- packages/sqlite/package.json
sqlite - upgrading ts-node and tsdk to latest
> sqlite - upgrading ts-node and tsdk to latest

- packages/sqlite/package.json
sqlite - upgrading sqlite3 to 5.1.7
> sqlite - upgrading sqlite3 to 5.1.7

- packages/postgres/package.json
postgres - upgrading @types/pg to 8.10.9
> postgres - upgrading @types/pg to 8.10.9

- packages/mysql/package.json
mysql - upgrading ts-node and tsd to latest
> mysql - upgrading ts-node and tsd to latest

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.7.1
> mysql - upgrading mysql2 to 3.7.1

- packages/etcd/package.json
> etcd - upgrading c8 to 9.1.0

- packages/offline/package.json
offline - upgrading tsd to 0.30.4
> offline - upgrading tsd to 0.30.4

- packages/tiered/package.json
tiered - fixing the nodejs version to 16
> tiered - fixing the nodejs version to 16

- packages/redis/package.json
redis - upgrading tsd to 0.30.4
> redis - upgrading tsd to 0.30.4

- packages/memcache/package.json
memcache - upgrading memjs to 1.3.2
> memcache - upgrading memjs to 1.3.2

- packages/compress-gzip/package.json
compress-gzip - upgrading tsd and @typescript-eslint/parser to latest
> compress-gzip - upgrading tsd and @typescript-eslint/parser to latest

- .github/workflows/tests.yaml
- packages/postgres/package.json
postgres - upgrading @types/pg to 8.11.0
> postgres - upgrading @types/pg to 8.11.0

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.9.1
> mysql - upgrading mysql2 to 3.9.1

- packages/etcd/package.json
- packages/etcd/src/index.ts
> etcd - upgrading xo to 0.57.0

- .github/workflows/tests.yaml
https://nodejs.org/en/blog/announcements/nodejs16-eol
> no longer supporting node 16 - end of life

- .github/workflows/tests.yaml
> no longer supporting node 16

- packages/redis/package.json
redis - upgrading tsd to 0.30.7
> redis - upgrading tsd to 0.30.7

- packages/offline/package.json
test-suite - updating tsd to 0.30.7
> test-suite - updating tsd to 0.30.7

- packages/compress-gzip/package.json
compress-gzip - updating @typescript-eslint/parser to 7.1.0
> compress-gzip - updating @typescript-eslint/parser to 7.1.0

- packages/compress-brotli/package.json
compress-brotli - upgrading webpack to 5.90.3
> compress-brotli - upgrading webpack to 5.90.3

- packages/keyv/package.json
keyv - upgrading tsd and eslint to latest
> keyv - upgrading tsd and eslint to latest

- packages/sqlite/package.json
sqlite - upgrading tsd to 0.30.7
> sqlite - upgrading tsd to 0.30.7

- packages/postgres/package.json
postgres - upgrading @types/pg and tsd to latest
> postgres - upgrading @types/pg and tsd to latest

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.9.2
> mysql - upgrading mysql2 to 3.9.2

- packages/etcd/package.json
> etcd - upgrading xo to 0.58.0

- packages/etcd/package.json
etcd - upgrading typescript, tsd, and webpack to latest
> etcd - upgrading typescript, tsd, and webpack to latest

- packages/tiered/package.json
tiered - upgrading c8 to 9.1.0
> tiered - upgrading c8 to 9.1.0

- packages/tiered/package.json
tiered - upgrading eslint to 8.57.0
> tiered - upgrading eslint to 8.57.0

- packages/compress-gzip/package.json
compress-gzip - upgrading modules to latest
> compress-gzip - upgrading modules to latest

- packages/etcd/package.json
etcd - upgrading c8 and webpack
> etcd - upgrading c8 and webpack

- packages/keyv/package.json
keyv - upgrading eslint and tsd to latest
> keyv - upgrading eslint and tsd to latest

- packages/mongo/package.json
mongo - upgrading tsd and @ava/typescript to latest
> mongo - upgrading tsd and @ava/typescript to latest

- packages/sqlite/package.json
sqlite - upgrading tsd to 0.31.0
> sqlite - upgrading tsd to 0.31.0

- packages/postgres/package.json
postgres - upgrading pg to 8.11.5
> postgres - upgrading pg to 8.11.5

- packages/etcd/package.json
etcd - upgrading webpack tsd and typescript to latest
> etcd - upgrading webpack tsd and typescript to latest

- packages/compress-brotli/src/index.ts
- packages/compress-gzip/src/index.ts
removing the bad promise value on the compression adapters
> removing the bad promise value on the compression adapters

- packages/serialize/package.json
- packages/serialize/test/test.ts
updating tests and also modules to latest
> updating tests and also modules to latest

- packages/redis/package.json
redis - upgrading tsd to 0.31.0
> redis - upgrading tsd to 0.31.0

- packages/redis/package.json
redis - upgrading ioredis to 5.4.1
> redis - upgrading ioredis to 5.4.1

- packages/offline/package.json
offline - upgrading tsd to 0.31.0
> offline - upgrading tsd to 0.31.0

- packages/compress-brotli/package.json
compress-brotli - upgrading webpack to 5.91.0
> compress-brotli - upgrading webpack to 5.91.0

- packages/compress-gzip/package.json
compress-gzip - upgrading eslint to 9.2.0
> compress-gzip - upgrading eslint to 9.2.0

- package.json
mono - upgrading c8 to 9.1.0 and modules to latest
> mono - upgrading c8 to 9.1.0 and modules to latest

- packages/compress-gzip/package.json
compress-gzip - removing eslint parser as no longer needed
> compress-gzip - removing eslint parser as no longer needed

- packages/mongo/package.json
- packages/mongo/src/index.ts
- packages/mongo/test/test.ts
mongo - upgrading to latest mongodb driver and removing pify
> mongo - upgrading to latest mongodb driver and removing pify

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.9.7
> mysql - upgrading mysql2 to 3.9.7

- packages/etcd/package.json
etcd - upgrading typescript to 5.4.5 and removing ava
> etcd - upgrading typescript to 5.4.5 and removing ava

- packages/tiered/package.json
tiered - upgrading eslint to 9.3.0
> tiered - upgrading eslint to 9.3.0

- packages/keyv/package.json
keyv - removing pify as no longer needed
> keyv - removing pify as no longer needed

- packages/memcache/package.json
memcache - upgrading buffer to 6.0.3
> memcache - upgrading buffer to 6.0.3

- packages/postgres/package.json
postgres - upgrading pg to 8.12.0
> postgres - upgrading pg to 8.12.0

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.10.1
> mysql - upgrading mysql2 to 3.10.1

- packages/etcd/package.json
etcd - upgrading webpack and c8 to latest
> etcd - upgrading webpack and c8 to latest

- packages/tiered/package.json
tiered - upgrading c8 and eslint to latest
> tiered - upgrading c8 and eslint to latest

- packages/compress-brotli/LICENSE
- packages/compress-brotli/package.json
- packages/compress-gzip/LICENSE
- packages/compress-gzip/package.json
- packages/etcd/LICENSE
- packages/etcd/package.json
- packages/keyv/LICENSE
- packages/keyv/package.json
- packages/memcache/LICENSE
- packages/memcache/package.json
- packages/mongo/LICENSE
- packages/mongo/package.json
- packages/mysql/LICENSE
- packages/mysql/package.json
- packages/offline/LICENSE
- packages/offline/package.json
- packages/postgres/LICENSE
- packages/postgres/package.json
- packages/redis/LICENSE
- packages/redis/package.json
- packages/serialize/LICENSE
- packages/serialize/package.json
- packages/sqlite/LICENSE
- packages/sqlite/package.json
- packages/test-suite/LICENSE
- packages/test-suite/package.json
- packages/tiered/LICENSE
- packages/tiered/package.json
updating to distribute the LISCENCE file 
Fixing #1082
> updating to distribute the LISCENCE file

- packages/mongo/src/index.ts
- packages/mongo/src/types.ts
- packages/mongo/test/test.ts
Support iterator on MongoDb adapter with GridFS enabled
> #1087 Support iterator on MongoDb adapter with GridFS enabled

- package.json
- packages/test-suite/package.json
> mono - upgrading xo to 0.59.0

- package.json
mono - upgrading typescript and webpack to latest
> mono - upgrading typescript and webpack to latest

- package.json
mono - upgrading vitest to 2.0.4
> mono - upgrading vitest to 2.0.4

- packages/sqlite/package.json
- packages/sqlite/src/index.ts
- packages/sqlite/test/test.ts
sqlite - upgrading xo to 0.59.2
> sqlite - upgrading xo to 0.59.2

- packages/mysql/package.json
mysql - upgrading xo to 0.59.2
> mysql - upgrading xo to 0.59.2

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.10.3
> mysql - upgrading mysql2 to 3.10.3

- packages/etcd/package.json
> etcd - upgrading xo to 0.59.2

- packages/tiered/package.json
tiered - upgrading xo to 0.59.2
> tiered - upgrading xo to 0.59.2

- packages/website/package.json
updating website issue with rendering code
> updating website issue with rendering code

- packages/compress-brotli/README.md
- packages/compress-gzip/README.md
- packages/etcd/README.md
- packages/keyv/README.md
- packages/keyv/test/test.ts
- packages/memcache/README.md
- packages/mongo/README.md
- packages/mysql/README.md
- packages/offline/README.md
- packages/postgres/README.md
- packages/redis/README.md
- packages/serialize/README.md
- packages/sqlite/README.md
- packages/test-suite/README.md
- packages/tiered/README.md
- packages/website/site/docs/v4-to-v5.md
- packages/website/src/docs.ts
> updating docs to v5

- packages/keyv/README.md
removing adapter from options as no longer needed
> removing adapter from options as no longer needed

- package.json
- packages/third-party/docker-compose.yaml
- packages/third-party/package.json
- packages/third-party/tests/third-party.test.ts
- packages/website/src/docs.ts
> Add third-party test with keyv5

- packages/test-suite/src/types.ts
- packages/third-party/tests/third-party.test.ts
> Add any support for store tests

- packages/keyv/README.md
fixes #1114
updating readme on addHandler for hooks for #1114
> updating readme on addHandler for hooks

- package.json
mono - upgrading webpack and @types/node to latest
> mono - upgrading webpack and @types/node to latest

- packages/keyv/package.json
keyv - upgrading tsd to 0.31.2
> keyv - upgrading tsd to 0.31.2

- packages/memcache/package.json
memcache - upgrading keyv and tsd to latest
> memcache - upgrading keyv and tsd to latest

- packages/redis/package.json
redis - upgrading keyv and tsd to latest
> redis - upgrading keyv and tsd to latest

- packages/test-suite/package.json
test-suite - upgrading keyv to 5.0.1
> test-suite - upgrading keyv to 5.0.1

- packages/offline/package.json
offline - upgrading keyv and tsd to latest
> offline - upgrading keyv and tsd to latest

- packages/compress-brotli/package.json
compress-brotli - upgrading keyv to v5.0.1
> compress-brotli - upgrading keyv to v5.0.1

- package.json
- packages/compress-brotli/package.json
- packages/compress-gzip/package.json
- packages/etcd/package.json
- packages/keyv/package.json
- packages/memcache/package.json
- packages/mongo/package.json
- packages/mysql/package.json
- packages/offline/package.json
- packages/postgres/package.json
- packages/redis/package.json
- packages/serialize/package.json
- packages/sqlite/package.json
- packages/test-suite/package.json
- packages/tiered/package.json
- packages/website/package.json
- packages/website/src/docs.ts
compress-gzip - updating rimraf and tsd
> compress-gzip - updating rimraf and tsd

- packages/postgres/package.json
- packages/sqlite/package.json
- packages/test-suite/package.json
- packages/test-suite/src/api.ts
- packages/test-suite/src/compression.ts
- packages/test-suite/src/index.ts
- packages/test-suite/src/iterator.ts
- packages/test-suite/src/namespace.ts
- packages/test-suite/src/values.ts
- packages/tiered/package.json
sqlite - upgrade keyv to 5.0.1
> sqlite - upgrade keyv to 5.0.1

- packages/postgres/package.json
postgres - upgrading pg to 8.13.0
> postgres - upgrading pg to 8.13.0

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.11.3
> mysql - upgrading mysql2 to 3.11.3

- packages/etcd/package.json
etcd - upgrading modules to lastest
> etcd - upgrading modules to lastest

- packages/website/package.json
website - upgrading docula to 0.9.1
> website - upgrading docula to 0.9.1

- package.json
mono - upgrading modules to latest such as vitest and tsup
> mono - upgrading modules to latest such as vitest and tsup

- packages/third-party/package.json
- packages/third-party/tests/third-party.test.ts
third-party - upgrading and validating keyv-file
> third-party - upgrading and validating keyv-file

- packages/keyv/package.json
- packages/keyv/src/index.ts
keyv - upgrading keyv to v5.0.2 and on() as a void return
> keyv - upgrading keyv to v5.0.2 and on() as a void return

- packages/postgres/package.json
- packages/postgres/src/pool.ts
postgres - updating ESM fix on Pool from pg
Issue: #1137 
Related Issue: https://github.com/brianc/node-postgres/issues/3060#issuecomment-1748047884
> postgres - updating ESM fix on Pool from pg

- packages/keyv/README.md
- packages/keyv/src/index.ts
- packages/keyv/test/test.ts
- packages/memcache/test/test.ts
> Add generic type support for Keyv class and improve type safety

- docker-compose.yaml
- package.json
- test-services-start.sh
- test-services-stop.sh
keyv - fixing test:services start and stop
> keyv - fixing test:services start and stop

- package.json
mono - upgrading webpack to 5.95.0
> mono - upgrading webpack to 5.95.0

- package.json
mono - upgrading vitest to 2.1.2
> mono - upgrading vitest to 2.1.2

- packages/memcache/package.json
memcache - upgrading keyv to 5.0.3
> memcache - upgrading keyv to 5.0.3

- packages/redis/package.json
redis - upgrading keyv to 5.0.3
> redis - upgrading keyv to 5.0.3

- packages/test-suite/package.json
test-suite - upgrading keyv and vitest to latest
> test-suite - upgrading keyv and vitest to latest

- packages/offline/package.json
offline - upgrading keyv to 5.0.3
> offline - upgrading keyv to 5.0.3

- packages/compress-brotli/package.json
compress-brotli - moving keyv as a * dependency
> compress-brotli - moving keyv as a * dependency

- packages/compress-gzip/package.json
compress-gzip - adding in keyv as * dependency
> compress-gzip - adding in keyv as * dependency

- packages/offline/README.md
- packages/offline/package.json
- packages/tiered/README.md
- packages/tiered/package.json
Deprecating Offline and Tiered Mode for Cacheable
> Deprecating Offline and Tiered Mode for Cacheable

- .github/workflows/codecov.yaml
- .github/workflows/deploy-website.yml
- .github/workflows/tests.yaml
- .gitignore
- CONTRIBUTING.md
- README.md
- package.json
- packages/compress-brotli/package.json
- packages/compress-gzip/package.json
- packages/etcd/package.json
- packages/keyv/package.json
- packages/memcache/README.md
- packages/memcache/package.json
- packages/mongo/package.json
- packages/mysql/package.json
- packages/offline/package.json
- packages/postgres/README.md
- packages/postgres/package.json
- packages/redis/package.json
- packages/serialize/package.json
- packages/sqlite/package.json
- packages/test-suite/package.json
- packages/tiered/package.json
- packages/valkey/package.json
- packages/website/package.json
- pnpm-workspace.yaml
> migration to pnpm from yarn

- packages/valkey/README.md
- packages/valkey/package.json
- packages/valkey/src/index.ts
- packages/valkey/src/types.ts
- packages/valkey/test/test.ts
valkey - adding in docs and createKeyv helper function
> valkey - adding in docs and createKeyv helper function

- packages/sqlite/test/test.ts
sqlite - multiple namespace instance testing on a single store
> sqlite - multiple namespace instance testing on a single store

- package.json
mono - upgrading vitest and typescript to latest
> mono - upgrading vitest and typescript to latest

- packages/sqlite/package.json
- packages/sqlite/src/index.ts
sqlite - adding in createKeyv and making Keyv dependency a star
> sqlite - adding in createKeyv and making Keyv dependency a star

- packages/postgres/README.md
- packages/postgres/package.json
- packages/postgres/src/index.ts
- packages/postgres/test/test.ts
Postgres - adding in create keyv as helper function
> Postgres - adding in create keyv as helper function

- packages/mysql/package.json
mysql - moving Keyv to star dependency
> mysql - moving Keyv to star dependency

- packages/etcd/package.json
etcd - upgrading typescript and webpack to latest
> etcd - upgrading typescript and webpack to latest

- packages/website/package.json
website - upgrading to using tsx over ts-node
> website - upgrading to using tsx over ts-node

- packages/keyv/package.json
- packages/keyv/src/event-manager.ts
- packages/keyv/test/event-manager.test.ts
keyv - adding in once event handler
> keyv - adding in once event handler

- packages/keyv/src/generic-store.ts
- packages/keyv/test/generic-store.test.ts
keyv - adding in generic store
> keyv - adding in generic store

- package.json
mono - upgrading vitest to 2.1.4
> mono - upgrading vitest to 2.1.4

- package.json
mono - upgrading tsup and mono to latest
> mono - upgrading tsup and mono to latest

- packages/memcache/package.json
memcache - upgrading typescript 5.6.3
> memcache - upgrading typescript 5.6.3

- packages/keyv/src/index.ts
> keyv - adding in jsdoc

- packages/keyv/src/index.ts
keyv - adding in additional jsdoc for clear, has, and disconnect
> keyv - adding in additional jsdoc for clear, has, and disconnect

- packages/keyv/src/index.ts
keyv - handling the namespace outside of opts
> keyv - handling the namespace outside of opts

- packages/keyv/README.md
- packages/keyv/src/index.ts
- packages/keyv/test/test.ts
keyv - adding in compress and decompress properties
> keyv - adding in compress and decompress properties

- packages/keyv/README.md
- packages/keyv/src/index.ts
- packages/keyv/test/test.ts
keyv - adding compression property
> keyv - adding compression property

- packages/keyv/README.md
- packages/keyv/src/index.ts
- packages/keyv/test/test.ts
Keyv - adding in use key prefix option
> Keyv - adding in use key prefix option

- packages/keyv/README.md
- packages/keyv/src/index.ts
- packages/keyv/test/test.ts
Keyv  - if there is no namespace then it will not prefix the key
> Keyv  - if there is no namespace then it will not prefix the key 

- packages/keyv/src/index.ts
Keyv  - moving to compression adapters just doing compress / decompress
> Keyv  - moving to compression adapters just doing compress / decompress

- packages/keyv/src/index.ts
- packages/keyv/test/test.ts
Keyv - handing complex objects with no serialize / deserialize
> Keyv - handing complex objects with no serialize / deserialize

- packages/redis/README.md
- packages/redis/src/index.ts
redis - updating the readme documentation and testing Keyv
> redis - updating the readme documentation and testing Keyv

- packages/valkey/README.md
- packages/valkey/src/index.ts
- packages/valkey/src/types.ts
- packages/valkey/test/test.ts
valkey - fixing items by moving back to useRedisSets
> valkey - fixing items by moving back to useRedisSets

- packages/valkey/package.json
valkey - upgrading iovalkey to 0.2.1
> valkey - upgrading iovalkey to 0.2.1

- packages/website/site/docs/caching/caching-koa.md
- packages/website/site/docs/caching/caching-nestjs.md
- packages/website/site/docs/caching/caching-node.md
updating remaining caching docs with cacheable using keyv
> Website  - updating remaining caching docs with cacheable using keyv

- packages/redis/README.md
redis - adding in additional documentation for clustering
> redis - adding in additional documentation for clustering

- packages/postgres/package.json
postgres - upgrading pg to 8.13.1
> postgres - upgrading pg to 8.13.1

- packages/mysql/package.json
Mysql - upgrading mysql2 to 3.11.4
> Mysql - upgrading mysql2 to 3.11.4

- package.json
mono - upgrading vitest to 2.1.5
> mono - upgrading vitest to 2.1.5

- packages/redis/package.json
- packages/redis/src/index.ts
- packages/redis/test/suite.ts
- packages/redis/test/test.ts
- packages/redis/vitest.config.ts
redis - fixing lint issues and clean up
> redis - fixing lint issues and clean up

- .npmrc
mono - adding in link-workspace-packages
> mono - adding in link-workspace-packages

- packages/keyv/src/index.ts
keyv - adding in valkey as iterable
> keyv - adding in valkey as iterable

- packages/redis/README.md
redis - updating readme on clear and namespace support and fix for #1222
> redis - updating readme on clear and namespace support

- package.json
- packages/compress-brotli/package.json
- packages/compress-gzip/package.json
- packages/etcd/package.json
- packages/keyv/package.json
- packages/memcache/package.json
- packages/mongo/package.json
- packages/mysql/package.json
- packages/postgres/package.json
- packages/redis/package.json
- packages/serialize/package.json
- packages/sqlite/package.json
- packages/test-suite/package.json
- packages/valkey/package.json
Enhancing pnpm workspaces with local references
> Enhancing pnpm workspaces with local references

- packages/keyv/package.json
- packages/keyv/src/event-manager.ts
> keyv - upgrading xo to 0.60.0

- packages/memcache/package.json
memcache - upgrading xo to 0.60.0
> memcache - upgrading xo to 0.60.0

- packages/test-suite/package.json
test-suite - upgrading vitest to 2.1.8
> test-suite - upgrading vitest to 2.1.8

- packages/test-suite/README.md
> test-suite - fixing readme

- packages/redis/package.json
redis - upgrading xo to 0.60.0
> redis - upgrading xo to 0.60.0

- packages/redis/package.json
redis - upgrading vitest to 2.1.8
> redis - upgrading vitest to 2.1.8

- packages/compress-brotli/package.json
compress-brotli - upgrading xo to 0.60.0
> compress-brotli - upgrading xo to 0.60.0

- packages/compress-gzip/package.json
- packages/compress-gzip/src/index.ts
compress-gzip - upgrading xo to 0.60.0
> compress-gzip - upgrading xo to 0.60.0

- packages/etcd/package.json
> etcd - upgrading xo to 0.60.0

- packages/etcd/package.json
- packages/etcd/src/index.ts
- packages/etcd/test/test.ts
- packages/etcd/vitest.config.ts
Etcd - cleaning up dependencies and lint rules
> Etcd - cleaning up dependencies and lint rules

- README.md
**What kind of change does this PR introduce?**
It updates the README file to list _keyv-upstash_ as a third-party storage adapter.
> docs(README.md): add keyv-upstash as a third-party adapter

- .npmrc
> mono - removing npmrc

- packages/keyv/src/index.ts
> fix: improve keyv errors handling with store methods

- packages/keyv/src/index.ts
- packages/keyv/test/test.ts
ref: https://github.com/jaredwray/keyv/issues/1248
> fix: update keyv events errors handling

- packages/keyv/README.md
Minor tweaks at readme to reflect `emitErrors` option.
> docs: update README to include emitErrors option for Keyv

- packages/sqlite/package.json
sqlite - upgrading xo to 0.60.0
> sqlite - upgrading xo to 0.60.0

- packages/mysql/package.json
mysql - upgrading mysql2 to 3.11.5
> mysql - upgrading mysql2 to 3.11.5

- packages/valkey/package.json
> upgrading valkey to 0.60.0

- packages/website/package.json
website - upgrading docula to 0.9.6
> website - upgrading docula to 0.9.6

- package.json
- packages/serialize/package.json
serialize - upgrading typescript and tsd to latest
> serialize - upgrading typescript and tsd to latest

- package.json
mono - upgrading typescript types and webpack to latest
> mono - upgrading typescript types and webpack to latest

- packages/compress-brotli/package.json
- packages/compress-brotli/src/index.ts
- packages/compress-brotli/src/types.ts
- packages/compress-brotli/test/types.ts
- packages/compress-brotli/vitest.config.ts
compress-brotli - updating linting to be more inline
> compress-brotli - updating linting to be more inline

- packages/website/package.json
website - updating to not do build of website on build
> website - updating to not do build of website on build

- packages/compress-brotli/package.json
compress-brotli - chore: upgrading c8 to 10.1.3
> compress-brotli - chore: upgrading c8 to 10.1.3

- packages/keyv/src/generic-store.ts
- packages/keyv/test/generic-store.test.ts
keyv - feat: updating deleteMany function on generic storage adapter
> keyv - feat: updating deleteMany function on generic storage adapter

- packages/keyv/package.json
- packages/keyv/test/keyv-hooks.test.ts
- packages/keyv/test/test.ts
keyv - chore: removing import/no-named-as-default from lint
> keyv - chore: removing import/no-named-as-default from lint

- packages/keyv/package.json
- packages/keyv/src/generic-store.ts
- packages/keyv/src/hooks-manager.ts
- packages/keyv/src/index.ts
- packages/keyv/test/test.ts
- packages/keyv/vitest.config.ts
keyv - chore: removing xo lint rules from package.json
> keyv - chore: removing xo lint rules from package.json

- packages/website/site/docs/caching/caching-nestjs.md
website - fix: updating nestjs caching example
#1274
> website - fix: updating nestjs caching example

- packages/mysql/package.json
mysql - chore: upgrading mysql2 to 3.12.0
> mysql - chore: upgrading mysql2 to 3.12.0

- packages/etcd/package.json
etcd - chore: upgrading vitest to 3.0.2
> etcd - chore: upgrading vitest to 3.0.2

- packages/valkey/package.json
valkey - chore: upgrading valkeyio to 0.2.2
> valkey - chore: upgrading valkeyio to 0.2.2

- packages/website/package.json
website - chore: upgrading docula to 0.10.0
> website - chore: upgrading docula to 0.10.0

- package.json
mono - chore: upgrading typescript and @types/node to latest
> mono - chore: upgrading typescript and @types/node to latest

- README.md
- packages/compress-lz4/README.md
- packages/compress-lz4/package.json
- packages/keyv/README.md
- packages/keyv/test/test.ts
- packages/website/site/docs/index.md
compress-lz4 - clean up readme docs
> compress-lz4 - clean up readme docs

- packages/website/site/docs/caching/caching-nestjs.md
website - fix: updating wording from sqlite to redis
#1292
> website - fix: updating wording from sqlite to redis

- packages/keyv/package.json
keyv - chore: upgradinv vitest to 3.0.4
> keyv - chore: upgradinv vitest to 3.0.4

- packages/redis/package.json
- packages/test-suite/package.json
redis - chore: upgrading vitest to 3.0.4
> test-suite - chore: upgrading vitest to 3.0.4

- packages/compress-brotli/package.json
compress-brotli - chore: upgrading vitest to 3.0.4
> compress-brotli - chore: upgrading vitest to 3.0.4

- packages/compress-lz4/package.json
compress-lz4 - chore: upgrading vitest to 3.0.4
> compress-lz4 - chore: upgrading vitest to 3.0.4

- .github/workflows/codecov.yaml
- .github/workflows/tests.yaml
- package.json
- packages/website/site/docs/caching/caching-nestjs.md
website - fix: updating import spacing in caching-nestjs.md
> Fix import spacing in caching-nestjs.md

- packages/postgres/package.json
postgres - chore: upgrading pg to 8.13.3
> postgres - chore: upgrading pg to 8.13.3

- packages/etcd/package.json
etcd - chore: upgrading vitest to 3.0.5
> etcd - chore: upgrading vitest to 3.0.5

- packages/valkey/package.json
valkey - chore: upgrading iovalkey to 0.3.1
> valkey - chore: upgrading iovalkey to 0.3.1

- package.json
mono - chore: upgrading vitest to 3.0.5
> mono - chore: upgrading vitest to 3.0.5

- package.json
mono - chore: upgrading tsup and webpack to latest
> mono - chore: upgrading tsup and webpack to latest

- packages/keyv/package.json
- packages/keyv/src/generic-store.ts
- packages/keyv/src/index.ts
- packages/keyv/test/generic-store.test.ts
- packages/keyv/test/keyv-test.test.ts
- packages/redis/src/index.ts
keyv - feat: adding in support for many with setMany and set
> keyv - feat: adding in support for many with setMany and set

- packages/redis/test/test.ts
redis - chore: adding in unit test on reconnect strategy
> Redis   chore adding in unit test on reconnect strategy

- packages/redis/README.md
redis - chore: updating the documentation on events
> redis - chore: updating the documentation on events

- packages/redis/README.md
- packages/redis/src/index.ts
redis - allowing for graceful disconnect via quit and force option
> redis - feat: allowing for graceful disconnect via quit and force option

- packages/keyv/README.md
- packages/keyv/src/index.ts
- packages/keyv/test/keyv-test.test.ts
feat: adding in hasMany and has function
> feat: adding in hasMany and has function

- packages/keyv/package.json
keyv - chore: upgrading @faker-js/faker to 9.5.1
> keyv - chore: upgrading @faker-js/faker to 9.5.1

- packages/keyv/package.json
keyv - chore: upgrading vitest to 3.0.7
> keyv - chore: upgrading vitest to 3.0.7

- packages/redis/package.json
- packages/test-suite/package.json
redis - chore: upgrading vitest to 3.0.7
> redis - chore: upgrading vitest to 3.0.7

- packages/compress-brotli/package.json
compress-brotli - chore: upgrading vitest to 3.0.7
> compress-brotli - chore: upgrading vitest to 3.0.7

- packages/compress-lz4/package.json
compress-lz4 - chore: upgrading vitest to 3.0.7
> compress-lz4 - chore: upgrading vitest to 3.0.7

- .github/workflows/deploy-website.yml
- packages/compress-lz4/package.json
mono - fix: updating cloudflare deployment
> mono - fix: updating cloudflare deployment

- packages/keyv/src/generic-store.ts
- packages/keyv/src/index.ts
- packages/keyv/test/generic-store.test.ts
- packages/keyv/test/keyv-test.test.ts
- packages/redis/package.json
- packages/redis/src/index.ts
keyv - fix: KeyvStorageAdapter breaking type change
> keyv - fix: KeyvStorageAdapter breaking type change

- packages/redis/src/index.ts
redis - fix: handing a bad redis uri by emiting error
> redis - fix: handing a bad redis uri by emiting error

- packages/keyv/src/index.ts
- packages/keyv/test/keyv-test.test.ts
keyv - fix: when passing in undefined store property it defaults to Map
> keyv - fix: when passing in undefined store property it defaults to Map

- packages/postgres/src/index.ts
postgres - fix: removing console.log from options
> postgres - fix: removing console.log from options

- packages/postgres/package.json
postgres - chore: upgrading pg to 8.14.0
> postgres - chore: upgrading pg to 8.14.0

- packages/mysql/package.json
mysql - chore: upgrading mysql2 to 3.13.0
> mysql - chore: upgrading mysql2 to 3.13.0

- packages/etcd/package.json
etcd - chore: upgrading vitest to 3.0.8
> etcd - chore: upgrading vitest to 3.0.8

- packages/website/package.json
website - chore: upgrading docual to 0.10.1
> website - chore: upgrading docual to 0.10.1

- package.json
mono - chore: upgrading vitest to 3.0.8
> mono - chore: upgrading vitest to 3.0.8

- packages/sqlite/README.md
**What kind of change does this PR introduce?**
Documentation update that I saw while I was using this in a project I have - think of this as a quick "pass-by-and-commit", but I figured the project would appreciate.
> sqlite - Fix mis-spelling in README.md

- packages/redis/package.json
- packages/redis/src/index.ts
- packages/test-suite/package.json
- packages/test-suite/src/values.ts
redis - fix: typecheck on vitest failing
> test-suite - fix: updating bignumber.js as the update was breaking

- packages/keyv/package.json
keyv - chore: upgrading vitest to 3.1.1
> keyv - chore: upgrading vitest to 3.1.1

- packages/keyv/package.json
keyv - chore: upgrading faker-js to 9.6.0
> keyv - chore: upgrading faker-js to 9.6.0

- packages/redis/README.md
- packages/redis/test/test.ts
redis - fix: updating readme to work with namespaces
#1350
> redis - fix: updating readme to work with namespaces

- packages/compress-brotli/package.json
compress-brotli - chore: upgrading vitest to 3.1.1
> compress-brotli - chore: upgrading vitest to 3.1.1

- packages/compress-lz4/package.json
compress-lz4 - chore: upgrading vitest to 3.1.1
> compress-lz4 - chore: upgrading vitest to 3.1.1

- README.md
mono - fix: removing tiered as that package is no longer used
mono - fix: removing tiered as that package is no longer used
> mono - fix: removing tiered as that package is no longer used

- README.md
mono - fix: updating readme with what is in repo
> mono - fix: updating readme with what is in repo

- package.json
mono - chore: upgrading vitest to 3.1.1
> mono - chore: upgrading vitest to 3.1.1

- packages/sqlite/package.json
sqlite - chore: upgrading tsd to 0.32.0
> sqlite - chore: upgrading tsd to 0.32.0

- packages/postgres/package.json
postgres - chore: upgrading tsd to 0.32.0
> postgres - chore: upgrading tsd to 0.32.0

- packages/postgres/package.json
postgres - chore: upgrading pg to 8.14.1
> postgres - chore: upgrading pg to 8.14.1

- packages/mysql/package.json
mysql - chore: upgrading mysql2 to 3.14.0
> mysql - chore: upgrading mysql2 to 3.14.0

- packages/etcd/package.json
etcd - chore: upgrading typescript to 5.8.3
> etcd - chore: upgrading typescript to 5.8.3

- packages/etcd/package.json
etcd - chore: upgrading vitest to 3.1.1
> etcd - chore: upgrading vitest to 3.1.1

- packages/valkey/package.json
valkey - chore: upgrading valkey to 0.32.0
> valkey - chore: upgrading valkey to 0.32.0

- packages/website/package.json
website - chore: upgrading docula to 0.11.1
> website - chore: upgrading docula to 0.11.1

- packages/serialize/package.json
serialize - chore: upgrading typescript to 5.8.3
> serialize - chore: upgrading typescript to 5.8.3

- packages/redis/package.json
redis - fix: moving Keyv to a peer dependency
#1378
> redis - fix: moving Keyv to a peer dependency

- packages/compress-gzip/package.json
compress-gzip - fix: moving Keyv to a peer dependency
> compress-gzip - fix: moving Keyv to a peer dependency

- packages/redis/README.md
redis - chore: adding in docs to install keyv and @keyv/redis
> redis - chore: adding in docs to install keyv and @keyv/redis

- packages/compress-lz4/package.json
compress-lz4 - fix: moving Keyv to a peer dependency
> compress-lz4 - fix: moving Keyv to a peer dependency

- packages/etcd/package.json
etcd - fix: moving Keyv to a peer dependency
> etcd - fix: moving Keyv to a peer dependency

- packages/postgres/package.json
postgres - fix: moving Keyv to a peer dependency
> postgres - fix: moving Keyv to a peer dependency

- packages/sqlite/package.json
sqlite - fix: moving Keyv to a peer dependency
> sqlite - fix: moving Keyv to a peer dependency

- packages/redis/package.json
- packages/redis/src/index.ts
- packages/redis/test/test.ts
feat: moving to @redis/client to reduce package size
#1392
> feat: moving to @redis/client to reduce package size

- packages/redis/README.md
redis - feat: updating docs for redis client
> redis - feat: updating docs for redis client

- packages/keyv/package.json
keyv - chore: upgrading vitest to 3.1.2
> keyv - chore: upgrading vitest to 3.1.2

- packages/keyv/package.json
keyv - chore: upgrading faker-js to 9.7.0
> keyv - chore: upgrading faker-js to 9.7.0

- packages/redis/package.json
redis - chore: upgrading vitest to 3.1.2
> redis - chore: upgrading vitest to 3.1.2

- packages/test-suite/package.json
test-suite - chore: upgrading vitest to 3.1.2
> test-suite - chore: upgrading vitest to 3.1.2

- packages/test-suite/package.json
test-suite - chore: upgrading bignumber.js to 9.3.0
> test-suite - chore: upgrading bignumber.js to 9.3.0

- packages/compress-brotli/package.json
compress-brotli - chore: upgrading vitest to 3.1.2
> compress-brotli - chore: upgrading vitest to 3.1.2

- packages/compress-gzip/package.json
compress-gzip - chore: upgrading tsd to 0.32.0
> compress-gzip - chore: upgrading tsd to 0.32.0

- packages/compress-lz4/package.json
compress-lz4 - chore: upgrading vitest to 3.1.2
> compress-lz4 - chore: upgrading vitest to 3.1.2

- packages/mongo/src/index.ts
- packages/mongo/test/test.ts
- [ x ] Followed the [Contributing](https://github.com/jaredwray/keyv/blob/main/CONTRIBUTING.md) guidelines.
- [ x ] Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
Bug fix for #1411
**NOTE**
While the test was added I was unable to run the tests, as there was an error with @keyv/test-suite
> mongo - fix: adding in the db key to use 

- packages/sqlite/src/index.ts
sqlite - fix: fixing database close to work correctly
> sqlite - fix: fixing database close to work correctly

- packages/sqlite/test/test.ts
sqlite - fix: updating tests to handle the close correctly
> sqlite - fix: updating tests to handle the close correctly

- packages/postgres/package.json
postgres - chore: upgrading pg to 8.16.0
> postgres - chore: upgrading pg to 8.16.0

- packages/postgres/vitest.config.ts
postgres - fix: removing types.ts from coverage report
> postgres - fix: removing types.ts from coverage report

- packages/mysql/package.json
- packages/mysql/vitest.config.ts
mysql - chore: upgrading mysql2 to 3.14.1
> mysql - chore: upgrading mysql2 to 3.14.1

- packages/etcd/package.json
etcd - chore: upgrading vitest to 3.1.3
> etcd - chore: upgrading vitest to 3.1.3

- packages/website/package.json
website - chore: upgrading tsx to 4.19.4
> website - chore: upgrading tsx to 4.19.4

- package.json
mono - chore: upgrading webpack to 5.99.8
> mono - chore: upgrading webpack to 5.99.8

- packages/mongo/vitest.config.ts
mongo - chore: fixing exlcudes
> mongo - chore: fixing exlcudes

- packages/memcache/package.json
memcache - fix: moving keyv to peerDependency
> memcache - fix: moving keyv to peerDependency

- package.json
- packages/test-suite/src/index.ts
- packages/test-suite/src/iterator.ts
- packages/test-suite/src/types.ts
- packages/test-suite/test/unit.ts
keyv - chore: upgrading xo to 1.1.0
> keyv - chore: upgrading xo to 1.1.0

- packages/memcache/package.json
memcache - chore: upgrading vitest to 3.2.3
> memcache - chore: upgrading vitest to 3.2.3

- packages/redis/package.json
- packages/redis/src/index.ts
- packages/redis/test/types.test-d.ts
- scripts/test-services-start.sh
redis - chore: upgrading xo to 1.1.0
> redis - chore: upgrading xo to 1.1.0

- packages/redis/package.json
redis - chore: upgrading vitest to 3.2.3
> redis - chore: upgrading vitest to 3.2.3

- packages/test-suite/package.json
test-suite - chore: upgrading vitest to 3.2.3
> test-suite - chore: upgrading vitest to 3.2.3

- packages/compress-lz4/package.json
compress-lz4 - chore: upgrading vitest to 3.2.3
> compress-lz4 - chore: upgrading vitest to 3.2.3

- packages/keyv/src/index.ts
- packages/keyv/test/keyv-test.test.ts
keyv - fix: handling serialization on setMany
> keyv - fix: handling serialization on setMany

- .github/workflows/codecov.yaml
- .github/workflows/deploy-website.yml
- .github/workflows/tests.yaml
mono - chore: updating the github actions with permissions
> mono - chore: updating the github actions with permissions

- packages/sqlite/package.json
- packages/sqlite/src/index.ts
- packages/sqlite/src/types.ts
sqlite - chore: upgrading xo to 1.1.0
> sqlite - chore: upgrading xo to 1.1.0

- packages/mysql/package.json
- packages/mysql/src/index.ts
- packages/mysql/test/ssl.ts
- packages/mysql/test/test.ts
mysql - chore: upgrading xo to 1.1.0
> mysql - chore: upgrading xo to 1.1.0

- packages/valkey/package.json
valkey - chore: upgrading vitest to 3.2.4
> valkey - chore: upgrading vitest to 3.2.4

- packages/valkey/package.json
- packages/valkey/vitest.config.ts
valkey - chore: upgrading iovalkey to 0.3.3
> valkey - chore: upgrading iovalkey to 0.3.3

- package.json
mono - chore: upgrading vitest to 3.2.4
> mono - chore: upgrading vitest to 3.2.4

- packages/valkey/src/index.ts
valkey - fix: fixing the createKeyv to work correctly
> valkey - fix: fixing the createKeyv to work correctly

- packages/valkey/src/index.ts
valkey - fix: fixing createKeyv to return Keyv instance
> valkey - fix: fixing createKeyv to return Keyv instance

- packages/redis/README.md
- packages/redis/src/index.ts
- packages/redis/test/get-client.test.ts
- packages/redis/test/set.test.ts
- packages/redis/test/test.ts
- packages/redis/vitest.config.ts
feat: updating the readme with errors and options
> feat: updating the readme with errors and options

- packages/keyv/package.json
keyv - chore: upgrading @faker-js/faker to 9.9.0
> keyv - chore: upgrading @faker-js/faker to 9.9.0

- packages/keyv/package.json
keyv - chore: upgrading vitest to 3.2.4
> keyv - chore: upgrading vitest to 3.2.4

- packages/memcache/package.json
memcache - chore: upgrading xo to 1.1.1
> memcache - chore: upgrading xo to 1.1.1

- packages/memcache/package.json
memcache - chore: upgrading vitest to 3.2.4
> memcache - chore: upgrading vitest to 3.2.4

- packages/redis/package.json
redis - chore: upgrading xo to 1.1.1
> redis - chore: upgrading xo to 1.1.1

- packages/redis/package.json
redis - chore: upgrading vitest to 3.2.4
> redis - chore: upgrading vitest to 3.2.4

- packages/redis/package.json
redis - chore: upgrading @faker-js/faker to 9.9.0
> redis - chore: upgrading @faker-js/faker to 9.9.0

- packages/compress-brotli/package.json
compress-brotli - chore: upgrading vitest to 3.2.4
> compress-brotli - chore: upgrading vitest to 3.2.4

- packages/compress-gzip/package.json
compress-gzip - chore: upgrading vitest to 3.2.4
> compress-gzip - chore: upgrading vitest to 3.2.4

- packages/compress-lz4/package.json
compress-lz4 - chore: upgrading lz4-napi to 2.9.0
> compress-lz4 - chore: upgrading lz4-napi to 2.9.0

- packages/compress-lz4/package.json
compress-lz4 - chore: upgrading vitest to 3.2.4
> compress-lz4 - chore: upgrading vitest to 3.2.4

- .github/workflows/codecov.yaml
- packages/bigmap/LICENSE
- packages/bigmap/README.md
- packages/bigmap/package.json
- packages/bigmap/src/index.ts
- packages/bigmap/test/index.test.ts
- packages/bigmap/tsconfig.json
- packages/bigmap/vitest.config.ts
bigmap - adding in bigmap for keyv
> bigmap - adding in bigmap for keyv

- packages/redis/src/index.ts
redis - fix: fixing the disconnect on error so it triggers
> redis - fix: fixing the disconnect on error so it triggers

- packages/keyv/README.md
- packages/keyv/src/index.ts
- packages/keyv/test/generic-store.test.ts
- packages/keyv/test/keyv-test.test.ts
- packages/redis/README.md
- packages/redis/src/index.ts
- packages/redis/test/delete.test.ts
- packages/redis/test/get-client.test.ts
- packages/redis/test/get.test.ts
- packages/redis/test/has.test.ts
- packages/redis/test/main.test.ts
- packages/redis/test/set.test.ts
keyv - feat: adding in throwErrors option
> keyv - feat: adding in throwErrors option

- packages/test-suite/package.json
- packages/test-suite/src/compression-adapter.ts
- packages/test-suite/src/helper.ts
- packages/test-suite/test/unit.ts
test-suite - feat: moving to internal compression adapter for testing
> test-suite - feat: moving to internal compression adapter for testing

- packages/keyv/src/index.ts
- packages/keyv/test/keyv-test.test.ts
Bug fix/performance improvement
This makes `getMany` call `deleteMany` on expired keys instead of deleting them serially (which is extremely slow if you have many keys expiring at once)
> keyv - fixed `getMany` serially awaiting expired key deletion

- packages/keyv/README.md
Fixes obvious wrong object destructuring in hook handler docs.
> docs: fix callback parameter in keyv hook handler.

- package.json
mono - chore: upgrading webpack to 5.100.2
> mono - chore: upgrading webpack to 5.100.2

- packages/mysql/package.json
mysql - chore: upgrading mysql2 to 3.14.2
> mysql - chore: upgrading mysql2 to 3.14.2

- packages/etcd/package.json
memcache - chore: upgrading xo to 1.2.1
> memcache - chore: upgrading xo to 1.2.1

- packages/valkey/package.json
valkey - chore: upgrading xo to 1.2.1
> valkey - chore: upgrading xo to 1.2.1

- packages/website/package.json
website - chore: upgrading docula to 0.13.1
> website - chore: upgrading docula to 0.13.1

- packages/serialize/package.json
- packages/serialize/src/index.ts
- packages/serialize/test/test.ts
serialize - chore: upgrading xo to 1.2.1
> serialize - feat: upgrading xo to 1.2.1 and clean up

- packages/valkey/src/index.ts
- packages/valkey/src/types.ts
- packages/valkey/test/test.ts
Fixes wrong types for valkey options as discussed in #1519.
> valkey - fix: use proper types for options

- packages/keyv/package.json
keyv - chore: upgrading xo to 1.2.1
> keyv - chore: upgrading xo to 1.2.1

- packages/keyv/README.md
- packages/keyv/src/index.ts
- packages/keyv/src/stats-manager.ts
- packages/keyv/test/generic-store.test.ts
- packages/keyv/test/get-raw.test.ts
- packages/keyv/test/keyv-test.test.ts
- packages/keyv/test/suite.test.ts
- packages/keyv/test/test.ts
- packages/keyv/vitest.config.ts
keyv - feat: adding in getRaw and getManyRaw
> keyv - feat: adding in getRaw and getManyRaw

- packages/redis/README.md
docs update: Added a detailed NestJS integration guide using @keyv/redis
Example repository using the steps from this guide:  
https://github.com/JardeFelicio/nest-redis-cache-example
Feel free to use it for testing or validation purposes.
> redis - feat: add step-by-step guide for using @keyv/redis with NestJS

- packages/redis/README.md
- packages/redis/src/index.ts
- packages/redis/test/sentinel.test.ts
- scripts/docker-compose-redis-sentinel.yaml
- scripts/test-services-start.sh
- scripts/test-services-stop.sh
redis - feat: support `createSentinel` connection when creating a `KeyvRedis` store
References #1347
> redis - feat: support redis sentinel for KeyvRedis store

- packages/memcache/package.json
memcche - chore: upgrading xo to 1.2.1
> memcche - chore: upgrading xo to 1.2.1

- packages/redis/package.json
redis - chore: upgrading hookified to 1.11.0
> redis - chore: upgrading hookified to 1.11.0

- packages/redis/package.json
redis - chore: upgrading @redis/client to 5.7.0
> redis - chore: upgrading @redis/client to 5.7.0

- packages/test-suite/package.json
test-suite - chore: upgrading bignumber.js to 9.3.1
> test-suite - chore: upgrading bignumber.js to 9.3.1

- packages/sqlite/package.json
sqlite - chore: upgrading xo to 1.2.2
> sqlite - chore: upgrading xo to 1.2.2

- packages/postgres/package.json
postgres - chore: upgrading xo and @types/pg to latest
> postgres - chore: upgrading xo and @types/pg to latest

- packages/mysql/package.json
mysql - chore: upgrading mysql2 to 3.14.3
> mysql - chore: upgrading mysql2 to 3.14.3

- packages/valkey/package.json
valkey - chore: upgrading xo to 1.2.2
> valkey - chore: upgrading xo to 1.2.2

- packages/serialize/package.json
serialize - chore: upgrading xo to 1.2.2
> serialize - chore: upgrading xo to 1.2.2

- packages/serialize/package.json
serialize - chore: upgrading typescript to 5.9.2
> serialize - chore: upgrading typescript to 5.9.2

- packages/redis/README.md
redis - fixing readme to be correct on KeyvRedisOptions
> redis - fix: readme to be correct on KeyvRedisOptions

- .github/workflows/codecov.yaml
fix: updating codecov to get a fix going
> fix: updating codecov to get a fix going

- .gitignore
website - chore: fixing docs on caching to not be ignored
> website - chore: fixing docs on caching to not be ignored

- packages/redis/src/index.ts
- packages/redis/test/cluster.test.ts
redis - fix: on cluster it cannot do multi()
> redis - fix: on cluster it cannot do multi()

- packages/dynamo/README.md
- packages/dynamo/src/index.ts
- packages/dynamo/test/test.ts
dynamo - feat: exposing the client for better usage
#1563
> dynamo - feat: exposing the client for better usage

- package.json
serialize - chore: upgrading @biomejs/biome to 2.2.3
> serialize - chore: upgrading @biomejs/biome to 2.2.3

- packages/dynamo/package.json
dynamo - chore: upgrading @biomejs/biome to 2.2.3
> dynamo - chore: upgrading @biomejs/biome to 2.2.3

- packages/dynamo/package.json
dynamo - chore: upgrading @aws-sdk to 3.883.0
> dynamo - chore: upgrading @aws-sdk to 3.883.0

- packages/compress-brotli/package.json
compress-brotli - chore: upgrading @biomejs/biome to 2.2.3
> compress-brotli - chore: upgrading @biomejs/biome to 2.2.3

- packages/compress-gzip/package.json
compress-gzip - chore: upgrading @biomejs/biome to 2.2.4
> compress-gzip - chore: upgrading @biomejs/biome to 2.2.4

- packages/mysql/package.json
mysql - chore: upgrading biome to 2.2.4
> mysql - chore: upgrading biome to 2.2.4

- packages/postgres/package.json
postgres - chore: upgrading biom to 2.2.4
> postgres - chore: upgrading biom to 2.2.4

- packages/bigmap/package.json
bigmap - chore: upgrading @faker-js/faker to 10.0.0
> bigmap - chore: upgrading @faker-js/faker to 10.0.0

- packages/bigmap/package.json
- packages/compress-brotli/package.json
- packages/compress-gzip/package.json
- packages/compress-lz4/package.json
- packages/dynamo/package.json
- packages/etcd/package.json
- packages/keyv/package.json
- packages/memcache/package.json
- packages/mongo/package.json
- packages/mysql/package.json
- packages/postgres/package.json
- packages/redis/package.json
- packages/serialize/package.json
- packages/sqlite/package.json
- packages/test-suite/package.json
- packages/valkey/package.json
mono - chore:  updating biome lint and checks
> mono - chore:  updating biome lint and checks

- packages/mysql/src/index.ts
mysql - chore: updating to not use deprecated OkPacket
> mysql - chore: updating to not use deprecated OkPacket

- packages/keyv/README.md
feat: adding in stats documentation
> feat: adding in stats documentation

- packages/bigmap/package.json
bigmap - feat: moving to node 18
> bigmap - feat: moving to node 18

- packages/bigmap/package.json
bigmap - chore: upgrading hookified to 1.12.1
> bigmap - chore: upgrading hookified to 1.12.1

- packages/etcd/package.json
etcd - chore: upgrading biome to 2.2.4
> etcd - chore: upgrading biome to 2.2.4

- packages/dynamo/package.json
dynamo - chore: upgrading biome to 2.2.4
> dynamo - chore: upgrading biome to 2.2.4

- packages/dynamo/package.json
dynamo - upgrading @aws-sdk/dynamo to 3.896.0
> dynamo - upgrading @aws-sdk/dynamo to 3.896.0

- packages/mongo/package.json
mongo - fix: now using Keyv in workspace
> mongo - fix: now using Keyv in workspace

- packages/mongo/package.json
chore: upgrading mongodb to 6.20.0
> chore: upgrading mongodb to 6.20.0

- packages/dynamo/README.md
- packages/dynamo/package.json
- packages/dynamo/src/index.ts
- packages/dynamo/test/test.ts
- packages/mongo/package.json
dynamo - feat: adding in create keyv helper function
> dynamo - feat: adding in create keyv helper function

- packages/valkey/src/index.ts
- packages/valkey/test/test.ts
- scripts/docker-compose-arm64.yaml
- scripts/docker-compose.yaml
valkey - fix: removing sets namespace as it is not needed
#1612
> valkey - fix: removing sets namespace as it is not needed

- packages/keyv/package.json
keyv - chore: upgrading biome to 2.2.5
> keyv - chore: upgrading biome to 2.2.5

- packages/serialize/package.json
serialize - chore: upgrading biome to 2.2.5
> serialize - chore: upgrading biome to 2.2.5

- package.json
mono - chore: removing webpack as unneeded
> mono - chore: removing webpack as unneeded

- packages/compress-gzip/package.json
compress-gzip - chore: upgrading biome to 2.2.5
> compress-gzip - chore: upgrading biome to 2.2.5

- packages/compress-lz4/package.json
compress-lz4 - chore: upgrading biome to 2.2.5
> compress-lz4 - chore: upgrading biome to 2.2.5

- packages/bigmap/src/index.ts
- packages/bigmap/test/index.test.ts
bigmap - fix: adding in forEach code that works
> bigmap - fix: adding in forEach code that works

- packages/valkey/package.json
- packages/valkey/src/index.ts
valkey - fix: removing console.log that was added by accident
> valkey - fix: removing console.log that was added by accident
